export const SPECULATIVE_ASCII_FIRST = 0x20;
export const SPECULATIVE_ASCII_LAST = 0x7e;
export const SPECULATIVE_ASCII_COUNT = SPECULATIVE_ASCII_LAST - SPECULATIVE_ASCII_FIRST + 1;

export const SPECULATIVE_GLYPH_ENTRY_STRIDE = 6;
export const SPECULATIVE_GLYPH_ENTRY_X = 0;
export const SPECULATIVE_GLYPH_ENTRY_Y = 1;
export const SPECULATIVE_GLYPH_ENTRY_WIDTH = 2;
export const SPECULATIVE_GLYPH_ENTRY_HEIGHT = 3;
export const SPECULATIVE_GLYPH_ENTRY_OFFSET_X = 4;
export const SPECULATIVE_GLYPH_ENTRY_OFFSET_Y = 5;
export const SPECULATIVE_GLYPH_ENTRIES_LENGTH =
  SPECULATIVE_ASCII_COUNT * SPECULATIVE_GLYPH_ENTRY_STRIDE;
export const SPECULATIVE_GLYPH_ENTRIES_BYTES =
  SPECULATIVE_GLYPH_ENTRIES_LENGTH * Int32Array.BYTES_PER_ELEMENT;
