packages:
  - apps/*
  - packages/*

catalog:
  '@elysia/eden': 2.0.0-beta.5
  '@noble/post-quantum': 0.7.0
  '@serenity-kit/opaque': 1.1.0
  effect: 4.0.0-rc.111
  elysia: 2.0.0-beta.16
  exact-mirror: 1.2.6
  typebox: 1.3.23

linkWorkspacePackages: true
autoInstallPeers: true
strictPeerDependencies: false
onlyBuiltDependencies: []

packageExtensions:
  '@solidjs/web@2.0.0-rc.1':
    dependencies:
      csstype: 3.2.3
