# Generated by //tools/bazel/bun:generate_graph.py; do not edit.
load("@aspect_rules_js//js:defs.bzl", "js_library")

def declare_conformance_sources():
    js_library(name = "conformance_dependencies", deps = ["//:js_configuration", "//:node_modules/@noble/post-quantum", "//packages/auth:source__src__daemon-proof.ts", "//packages/shared:source__src__e2e-wasm-runtime.ts", "//packages/shared:source__src__transport.ts", "//packages/shared:source__test-vectors__noise-xxpsk3.json"])
    js_library(name = "conformance_sources", srcs = ["conformance.test.ts"], deps = [":conformance_dependencies"])
