"""Declare original archive Files for the five independent Cargo lock scopes."""
import argparse
import hashlib
import json
import pathlib
import tomllib

LOCKS = (
    "Cargo.lock",
    "tools/bolero/Cargo.lock",
    "tools/ownership-proofs/Cargo.lock",
    "tools/edge-kernel-profile/Cargo.lock",
    "tools/sim/Cargo.lock",
)
HOSTS = (
    ("darwin_arm64", "aarch64-apple-darwin", "osx", "aarch64"),
    ("darwin_x64", "x86_64-apple-darwin", "osx", "x86_64"),
    ("linux_arm64", "aarch64-unknown-linux-gnu", "linux", "aarch64"),
    ("linux_x64", "x86_64-unknown-linux-gnu", "linux", "x86_64"),
)


def catalog(root):
    packages = {}
    locks = {}
    for logical in LOCKS:
        data = (root / logical).read_bytes()
        locks[logical] = hashlib.sha256(data).hexdigest()
        document = tomllib.loads(data.decode())
        if not isinstance(document.get("package"), list):
            raise ValueError("Cargo lock has no package inventory")
        for package in document["package"]:
            source = package.get("source")
            if source is None:
                continue
            if source != "registry+https://github.com/rust-lang/crates.io-index":
                raise ValueError("Workspace acquisition requires original crates.io archive authority")
            name, version, checksum = (package.get(key) for key in ("name", "version", "checksum"))
            if not isinstance(name, str) or not name or not isinstance(version, str) or not version:
                raise ValueError("Cargo lock package identity is missing")
            if any(character in name + version for character in '/\\"\n\r'):
                raise ValueError("Cargo lock package identity is not an archive member")
            if not isinstance(checksum, str) or len(checksum) != 64 or any(character not in "0123456789abcdef" for character in checksum):
                raise ValueError("Original Cargo archive checksum is missing or malformed")
            key = name, version
            previous = packages.get(key)
            if previous is not None and previous != checksum:
                raise ValueError("Independent Cargo locks disagree on original archive identity")
            packages[key] = checksum
    return dict(sorted(packages.items())), locks


def repository(checksum):
    return "merkur_workspace_cargo_archive_" + checksum


def runtime_sources(root):
    logical = "tools/bazel/rust/runtime_inputs.json"
    document = json.loads((root / logical).read_text())
    if not isinstance(document, dict) or any(not isinstance(owner, str) or not owner or not isinstance(paths, list) for owner, paths in document.items()):
        raise ValueError("Workspace runtime source inventory must map original packages to File lists")
    selected = {logical}
    for paths in document.values():
        for path in paths:
            if not isinstance(path, str) or not path or "\\" in path or str(pathlib.PurePosixPath(path)) != path or pathlib.PurePosixPath(path).is_absolute() or any(part in {"", ".", ".."} for part in path.split("/")):
                raise ValueError("Workspace runtime source File path must be canonical and relative")
            selected.add(path)
    result = {}
    for path in sorted(selected):
        original = root / path
        if not original.is_file():
            raise ValueError("Workspace runtime source File is missing: " + path)
        package = pathlib.PurePosixPath(path).parent
        while str(package) != "." and not (root / package / "BUILD.bazel").is_file():
            package = package.parent
        label = "//" + ("" if str(package) == "." else str(package)) + ":" + str(pathlib.PurePosixPath(path).relative_to(package))
        result[label] = path
    return result


def render(root):
    packages, locks = catalog(root)
    runtime = runtime_sources(root)
    header = "# Generated by tools/bazel/rust/acquire/workspace-sdk.py. DO NOT EDIT.\n"
    guards = "".join('# %s sha256=%s\n' % item for item in locks.items())
    module = [header, guards, 'workspace_cargo_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")\n\n']
    for (name, version), checksum in packages.items():
        filename = name + "-" + version + ".crate"
        module.append('workspace_cargo_archive(\n    name = "%s",\n    urls = ["https://static.crates.io/crates/%s/%s"],\n    sha256 = "%s",\n    downloaded_file_path = "%s",\n)\n\n' % (repository(checksum), name, filename, checksum, filename))
    declaration = [header, guards, 'load(":sdk_rules.bzl", "cargo_acquisition_sdk")\n\n_WORKSPACE_ARCHIVES = {\n']
    for (name, version), checksum in packages.items():
        declaration.append('    "@%s//file": "%s@%s",\n' % (repository(checksum), name, version))
    declaration.append('}\n\n_WORKSPACE_LOCKS = %r\n\n_WORKSPACE_RUNTIME_SOURCES = %r\n\n' % (list(LOCKS), runtime))
    declaration.append('def declare_workspace_sdks():\n    """Declare each native host; qualification is separate from this provider."""\n')
    for suffix, host, os_name, cpu in HOSTS:
        declaration.append('    native.config_setting(name = "workspace_sdk_host_%s", constraint_values = ["@platforms//os:%s", "@platforms//cpu:%s"])\n' % (suffix, os_name, cpu))
        declaration.append('    cargo_acquisition_sdk(\n        name = "workspace_sdk_%s",\n        execution_host = "%s",\n        source_files = _WORKSPACE_RUNTIME_SOURCES,\n        source_inputs = ["//tools/bazel/verification:production_acquisition_sources", "//tools:production_acquisition_sources"],\n        locks = _WORKSPACE_LOCKS,\n        archives = _WORKSPACE_ARCHIVES,\n        target_compatible_with = ["@platforms//os:%s", "@platforms//cpu:%s"],\n        exec_compatible_with = ["@platforms//os:%s", "@platforms//cpu:%s"],\n        tags = ["manual"],\n    )\n' % (suffix, host, os_name, cpu, os_name, cpu))
    declaration.append('    native.alias(\n        name = "production_sdk",\n        actual = select({\n')
    for suffix, *_ in HOSTS:
        declaration.append('            ":workspace_sdk_host_%s": ":workspace_sdk_%s",\n' % (suffix, suffix))
    declaration.append('            "//conditions:default": ":workspace_sdk_darwin_arm64",\n        }),\n        target_compatible_with = select({\n')
    for suffix, *_ in HOSTS:
        declaration.append('            ":workspace_sdk_host_%s": [],\n' % suffix)
    declaration.append('            "//conditions:default": ["@platforms//:incompatible"],\n        }),\n    )\n')
    return {"workspace-archives.MODULE.bazel": "".join(module), "workspace-sdk.bzl": "".join(declaration)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[4])
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parent)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render(args.root)
    if args.check:
        for name, data in outputs.items():
            if (args.output / name).read_text() != data:
                raise ValueError("Generated workspace SDK declaration is stale: " + name)
    else:
        # All original lock identities are validated before publishing any declaration.
        for name, data in outputs.items():
            (args.output / name).write_text(data)


if __name__ == "__main__":
    main()
