import { expect, test } from 'bun:test';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  renameSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { loadCapturedStaticProjections } from './ratchet-policy';
import { manifestFromInventory } from './snapshot';
import { withCapturedSourceTree } from './source-tree';
import {
  loadDeclaredStaticSources,
  loadStaticSources,
  type StaticSource,
  withStaticSources,
} from './static-sources';

function member(destination = 'generated/module.js'): StaticSource {
  const bytes = Buffer.from('export const value = 42;');
  return {
    destination,
    bytes,
    artifact: {
      path: 'bazel-out/native/bin/app/module.js',
      digest: createHash('sha256').update(bytes).digest('hex'),
      length: String(bytes.length),
    },
  };
}

function fixture(run: (root: string) => void): void {
  const root = mkdtempSync(path.join(os.tmpdir(), 'merkur-static-source-'));
  try {
    run(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

test('generated bytes are present only during analysis and owned paths are cleaned on success/failure', () => {
  fixture((root) => {
    const source = manifestFromInventory(root, [], 'commit');
    const item = member();
    for (const fail of [false, true]) {
      const run = () =>
        withStaticSources(
          root,
          source,
          [item],
          () => true,
          () => {
            expect(readFileSync(path.join(root, item.destination))).toEqual(
              Buffer.from(item.bytes),
            );
            if (fail) throw new Error('analysis failed');
          },
        );
      if (fail) expect(run).toThrow('analysis failed');
      else run();
      expect(existsSync(path.join(root, 'generated'))).toBe(false);
    }
  });
});

test('tracked, preexisting, aliased, unsafe and unignored generated destinations are rejected', () => {
  fixture((root) => {
    writeFileSync(path.join(root, 'source.ts'), 'source');
    const source = manifestFromInventory(root, ['source.ts'], 'commit');
    for (const destination of ['source.ts', 'source.ts/child', '../outside', '/absolute'])
      expect(() =>
        withStaticSources(
          root,
          source,
          [member(destination)],
          () => true,
          () => {},
        ),
      ).toThrow();
    const item = member();
    expect(() =>
      withStaticSources(
        root,
        source,
        [item],
        () => false,
        () => {},
      ),
    ).toThrow('ignore policy');
    mkdirSync(path.join(root, 'generated'));
    writeFileSync(path.join(root, item.destination), 'caller');
    expect(() =>
      withStaticSources(
        root,
        source,
        [item],
        () => true,
        () => {},
      ),
    ).toThrow();
    expect(readFileSync(path.join(root, item.destination), 'utf8')).toBe('caller');
    rmSync(path.join(root, 'generated'), { recursive: true });
    symlinkSync('.', path.join(root, 'generated'));
    expect(() =>
      withStaticSources(
        root,
        source,
        [item],
        () => true,
        () => {},
      ),
    ).toThrow('parent');
    expect(existsSync(path.join(root, 'module.js'))).toBe(false);
  });
});

test('byte mutations fail acceptance, and a moved parent alias cannot authorize outside cleanup', () => {
  fixture((root) => {
    const source = manifestFromInventory(root, [], 'commit');
    const item = member();
    expect(() =>
      withStaticSources(
        root,
        source,
        [item],
        () => true,
        () => {
          writeFileSync(path.join(root, item.destination), 'corrupted');
        },
      ),
    ).toThrow('changed');
    mkdirSync(path.join(root, 'existing'));
    const nested = member('existing/module.js');
    const moved = path.join(root, 'moved');
    expect(() =>
      withStaticSources(
        root,
        source,
        [nested],
        () => true,
        () => {
          renameSync(path.join(root, 'existing'), moved);
          symlinkSync('moved', path.join(root, 'existing'));
        },
      ),
    ).toThrow();
    expect(readFileSync(path.join(moved, 'module.js'))).toEqual(Buffer.from(nested.bytes));
  });
});

test('configured manifest and all projected bytes must agree with exact engine output evidence', async () => {
  const root = mkdtempSync(path.join(os.tmpdir(), 'merkur-static-producer-'));
  try {
    const item = member();
    const manifestPath = 'bazel-out/native/bin/app/projection.sources.json';
    const manifest = Buffer.from(
      JSON.stringify({
        producer: '@@//app:runtime',
        projection: '@@//app:projection',
        sources: [
          {
            artifact: 'app/module.js',
            destination: item.destination,
            size: item.bytes.length,
            sha256: item.artifact.digest,
          },
        ],
      }),
    );
    mkdirSync(path.dirname(path.join(root, manifestPath)), { recursive: true });
    writeFileSync(path.join(root, manifestPath), manifest);
    writeFileSync(path.join(root, item.artifact.path), item.bytes);
    const events = [
      {
        id: { namedSet: { id: 'manifest' } },
        namedSetOfFiles: {
          files: [
            {
              name: manifestPath,
              digest: createHash('sha256').update(manifest).digest('hex'),
              length: String(manifest.length),
            },
          ],
        },
      },
      {
        id: { namedSet: { id: 'sources' } },
        namedSetOfFiles: {
          files: [
            {
              name: item.artifact.path,
              digest: item.artifact.digest,
              length: item.artifact.length,
            },
          ],
        },
      },
      {
        id: { targetCompleted: { label: '//app:projection', configuration: { id: 'native' } } },
        completed: {
          success: true,
          outputGroup: [
            { name: 'projection_manifest', fileSets: [{ id: 'manifest' }] },
            { name: 'static_sources', fileSets: [{ id: 'sources' }] },
          ],
        },
      },
    ]
      .map((event) => JSON.stringify(event))
      .join('\n');
    const options = {
      events,
      engineRoot: root,
      label: '//app:projection',
      configuration: 'native',
      producer: '@@//app:runtime',
      destinations: [item.destination],
    };
    expect(await loadStaticSources(options)).toEqual([item]);
    for (const change of [
      { configuration: 'other' },
      { producer: '@@//other:runtime' },
      { destinations: [] },
    ])
      await expect(loadStaticSources({ ...options, ...change })).rejects.toThrow();
    writeFileSync(path.join(root, item.artifact.path), Buffer.alloc(item.bytes.length));
    await expect(loadStaticSources(options)).rejects.toThrow('differs');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('action projection manifests must match every typed configured File and exact logical destination', async () => {
  const root = mkdtempSync(path.join(os.tmpdir(), 'merkur-declared-projection-'));
  try {
    const item = member();
    mkdirSync(path.join(root, 'app'));
    writeFileSync(path.join(root, 'app/module.js'), item.bytes);
    writeFileSync(
      path.join(root, 'app/manifest.json'),
      JSON.stringify({
        producer: '@@//app:runtime',
        projection: '@@//app:projection',
        sources: [
          {
            artifact: 'app/module.js',
            destination: item.destination,
            size: item.bytes.length,
            sha256: item.artifact.digest,
          },
        ],
      }),
    );
    const options = {
      root,
      manifest: 'app/manifest.json',
      producer: '@@//app:runtime',
      projection: '@@//app:projection',
      files: [{ artifact: 'app/module.js', destination: item.destination }],
    };
    const result = await loadDeclaredStaticSources(options);
    expect(result[0]?.bytes).toEqual(Buffer.from(item.bytes));
    for (const change of [
      { files: [] },
      { files: [...options.files, ...options.files] },
      { files: [{ artifact: 'app/other.js', destination: item.destination }] },
      { files: [{ artifact: 'app/module.js', destination: 'other/destination.js' }] },
      { producer: '@@//other:runtime' },
      { projection: '@@//other:projection' },
    ])
      await expect(loadDeclaredStaticSources({ ...options, ...change })).rejects.toThrow();
    writeFileSync(path.join(root, 'app/module.js'), 'changed');
    await expect(loadDeclaredStaticSources(options)).rejects.toThrow();
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('captured static policy includes browser and package E2E projections together', async () => {
  const root = mkdtempSync(path.join(os.tmpdir(), 'merkur-complete-projection-'));
  try {
    const declarations = [
      ['apps/web', 'term_wasm_static_sources', 'term_wasm', 'apps/web/src/term-wasm/pkg'],
      ['apps/web', 'e2e_wasm_static_sources', 'e2e_wasm', 'apps/web/src/e2e-wasm/pkg'],
      [
        'apps/web',
        'graphics_wasm_static_sources',
        'graphics_wasm',
        'apps/web/src/graphics-wasm/pkg',
      ],
      ['packages/e2e-wasm', 'wasm_static_sources', 'e2e_wasm', 'packages/e2e-wasm/pkg'],
    ] as const;
    const projections = declarations.map(([owner, name, module, destination]) => {
      const producer = `@@//packages/${module.replaceAll('_', '-')}:wasm_artifacts`;
      const projection = `@@//${owner}:${name}`;
      const manifest = `${owner}/${name}.sources.json`;
      const sources = ['.js', '.d.ts', '_bg.wasm', '_bg.wasm.d.ts'].map((suffix) => {
        const artifact = `${owner}/${name}/${module}${suffix}`;
        const bytes = Buffer.from(`${projection}:${suffix}`);
        mkdirSync(path.dirname(path.join(root, artifact)), { recursive: true });
        writeFileSync(path.join(root, artifact), bytes);
        return {
          artifact,
          destination: `${destination}/${module}${suffix}`,
          size: bytes.length,
          sha256: createHash('sha256').update(bytes).digest('hex'),
        };
      });
      writeFileSync(path.join(root, manifest), JSON.stringify({ producer, projection, sources }));
      return {
        producer,
        projection,
        manifest,
        files: sources.map(({ artifact, destination }) => ({ artifact, destination })),
      };
    });
    const loaded = await loadCapturedStaticProjections(root, projections);
    expect(loaded).toHaveLength(16);
    expect(
      loaded.filter((file) => file.destination.startsWith('packages/e2e-wasm/pkg/')),
    ).toHaveLength(4);
    await expect(loadCapturedStaticProjections(root, projections.slice(0, 3))).rejects.toThrow(
      'Complete configured projection dependencies are required',
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

async function capturedFixture(
  run: (root: string, source: ReturnType<typeof manifestFromInventory>, tree: string) => void,
) {
  const parent = mkdtempSync(path.join(os.tmpdir(), 'merkur-captured-static-'));
  const sourceRoot = path.join(parent, 'source');
  const tree = path.join(parent, 'tree');
  const root = path.join(parent, 'private');
  try {
    for (const directory of [sourceRoot, tree, root]) mkdirSync(directory);
    for (const directory of [sourceRoot, tree]) {
      mkdirSync(path.join(directory, 'generated'));
      writeFileSync(path.join(directory, 'generated/module.js'), 'captured original', {
        mode: 0o444,
      });
      symlinkSync('generated/module.js', path.join(directory, 'alias.js'));
      symlinkSync('generated', path.join(directory, 'alias-directory'));
      writeFileSync(path.join(directory, '.gitignore'), 'generated\n');
    }
    const source = manifestFromInventory(
      sourceRoot,
      ['.gitignore', 'alias-directory', 'alias.js', 'generated/module.js'],
      'commit',
    );
    await withCapturedSourceTree({ tree, root, source }, async () => run(root, source, tree));
    expect(readdirSync(root)).toEqual([]);
  } finally {
    rmSync(parent, { recursive: true, force: true });
  }
}

test('active reconstruction loans readonly captured contents and restores exact original inode/mode/aliases', async () => {
  await capturedFixture((root, source, tree) => {
    const target = path.join(root, 'generated/module.js');
    const original = lstatSync(target);
    const alias = lstatSync(path.join(root, 'alias.js'));
    for (const fail of [false, true]) {
      const run = () =>
        withStaticSources(
          root,
          source,
          [member()],
          () => false,
          () => {
            expect(readFileSync(target)).toEqual(Buffer.from(member().bytes));
            expect(lstatSync(target).ino).toBe(original.ino);
            expect(lstatSync(target).mode & 0o777).toBe(0o600);
            expect(readFileSync(path.join(tree, 'generated/module.js'), 'utf8')).toBe(
              'captured original',
            );
            if (fail) throw new Error('analysis failed');
          },
        );
      if (fail) expect(run).toThrow('analysis failed');
      else run();
      expect(readFileSync(target, 'utf8')).toBe('captured original');
      expect(lstatSync(target).ino).toBe(original.ino);
      expect(lstatSync(target).mode & 0o777).toBe(0o444);
      expect(lstatSync(path.join(root, 'alias.js')).ino).toBe(alias.ino);
      expect(readlinkSync(path.join(root, 'alias.js'))).toBe('generated/module.js');
    }
  });
});

test('captured overlay rejects direct source, declared Tree, unowned copy and forged manifest loan', async () => {
  await capturedFixture((root, source, tree) => {
    for (const unowned of [source.root, tree])
      expect(() =>
        withStaticSources(
          unowned,
          source,
          [member()],
          () => false,
          () => {},
        ),
      ).toThrow('active private');
    const copy = path.join(path.dirname(root), 'copy');
    mkdirSync(path.join(copy, 'generated'), { recursive: true });
    writeFileSync(path.join(copy, 'generated/module.js'), 'captured original');
    expect(() =>
      withStaticSources(
        copy,
        source,
        [member()],
        () => true,
        () => {},
      ),
    ).toThrow('active private');
    for (const forged of [
      { ...source, root: copy },
      { ...source, digest: '0'.repeat(64) },
    ])
      expect(() =>
        withStaticSources(
          root,
          forged,
          [member()],
          () => false,
          () => {},
        ),
      ).toThrow('active private');
    expect(readFileSync(path.join(root, 'generated/module.js'), 'utf8')).toBe('captured original');
  });
});

test('ignore-policy and alias destinations remain refused inside an active reconstruction', async () => {
  await capturedFixture((root, source) => {
    for (const destination of [
      '.gitignore',
      '.git/info/exclude',
      'alias.js',
      'alias-directory/module.js',
    ])
      expect(() =>
        withStaticSources(
          root,
          source,
          [member(destination)],
          () => true,
          () => {},
        ),
      ).toThrow();
    expect(() =>
      withStaticSources(
        root,
        source,
        [member('generated/unignored.js')],
        () => false,
        () => {},
      ),
    ).toThrow('ignore policy');
    expect(readFileSync(path.join(root, '.gitignore'), 'utf8')).toBe('generated\n');
  });
});

test('temporary byte/mode mutations are rejected but the original journal is restored', async () => {
  await capturedFixture((root, source) => {
    const target = path.join(root, 'generated/module.js');
    for (const mutate of [() => writeFileSync(target, 'changed'), () => chmodSync(target, 0o700)]) {
      expect(() => withStaticSources(root, source, [member()], () => true, mutate)).toThrow();
      expect(readFileSync(target, 'utf8')).toBe('captured original');
      expect(lstatSync(target).mode & 0o777).toBe(0o444);
    }
  });
});

test('temporary namespace substitution restores held original without modifying a foreign replacement', async () => {
  const parent = mkdtempSync(path.join(os.tmpdir(), 'merkur-captured-static-substitution-'));
  try {
    const sourceRoot = path.join(parent, 'source');
    const tree = path.join(parent, 'tree');
    const root = path.join(parent, 'private');
    for (const directory of [sourceRoot, tree, root]) mkdirSync(directory);
    for (const directory of [sourceRoot, tree])
      writeFileSync(path.join(directory, 'module.js'), 'original');
    const source = manifestFromInventory(sourceRoot, ['module.js'], 'commit');
    await expect(
      withCapturedSourceTree({ tree, root, source }, async () => {
        const target = path.join(root, 'module.js');
        const original = lstatSync(target);
        expect(() =>
          withStaticSources(
            root,
            source,
            [member('module.js')],
            () => true,
            () => {
              renameSync(target, path.join(root, 'moved.js'));
              writeFileSync(target, 'foreign');
            },
          ),
        ).toThrow();
        expect(readFileSync(target, 'utf8')).toBe('foreign');
        expect(readFileSync(path.join(root, 'moved.js'), 'utf8')).toBe('original');
        expect(lstatSync(path.join(root, 'moved.js')).ino).toBe(original.ino);
      }),
    ).rejects.toThrow();
    expect(readFileSync(path.join(root, 'module.js'), 'utf8')).toBe('foreign');
  } finally {
    rmSync(parent, { recursive: true, force: true });
  }
});

test('reconstruction loan expires even when its consumer fails', async () => {
  const parent = mkdtempSync(path.join(os.tmpdir(), 'merkur-captured-static-expired-'));
  try {
    const sourceRoot = path.join(parent, 'source');
    const tree = path.join(parent, 'tree');
    const root = path.join(parent, 'private');
    for (const directory of [sourceRoot, tree, root]) mkdirSync(directory);
    for (const directory of [sourceRoot, tree])
      writeFileSync(path.join(directory, 'module.js'), 'original');
    const source = manifestFromInventory(sourceRoot, ['module.js'], 'commit');
    await expect(
      withCapturedSourceTree({ tree, root, source }, async () => {
        withStaticSources(
          root,
          source,
          [member('module.js')],
          () => true,
          () => {},
        );
        throw new Error('consumer failed');
      }),
    ).rejects.toThrow('consumer failed');
    writeFileSync(path.join(root, 'module.js'), 'original');
    expect(() =>
      withStaticSources(
        root,
        source,
        [member('module.js')],
        () => true,
        () => {},
      ),
    ).toThrow('active private');
    expect(readFileSync(path.join(root, 'module.js'), 'utf8')).toBe('original');
  } finally {
    rmSync(parent, { recursive: true, force: true });
  }
});
