import { expect, test } from 'bun:test';
import { lstat, readFile } from 'node:fs/promises';
import path from 'node:path';

const packages = [
  ['packages/e2e-wasm/pkg', 'e2e_wasm'],
  ['packages/term-wasm/pkg', 'term_wasm'],
  ['packages/graphics-wasm/pkg', 'graphics_wasm'],
  ['packages/graphics-codec-probe/pkg', 'graphics_codec_probe'],
  ['apps/web/src/e2e-wasm/pkg', 'e2e_wasm'],
  ['apps/web/src/term-wasm/pkg', 'term_wasm'],
  ['apps/web/src/graphics-wasm/pkg', 'graphics_wasm'],
] as const;

// The owning target declares these original package/runtime Trees as its data.
// Its normal launcher copies the same Files into this private runtime root.
const root = path.resolve(import.meta.dir, '../../..');
const runfiles = process.env.MERKUR_BAZEL_RUNFILES_ROOT;
if (runfiles === undefined || !path.isAbsolute(runfiles)) {
  throw new Error('Generated type inputs require original engine runfiles');
}

for (const [directory, moduleName] of packages) {
  test(`types consume original generated bytes at ${directory}`, async () => {
    for (const suffix of ['.js', '.d.ts', '_bg.wasm', '_bg.wasm.d.ts']) {
      const logical = `${directory}/${moduleName}${suffix}`;
      const copied = path.join(root, logical);
      const original = path.join(runfiles, '_main', logical);
      expect(copied).not.toBe(original);
      expect((await lstat(copied)).isFile()).toBe(true);
      expect(await readFile(copied)).toEqual(await readFile(original));
    }
  });
}
