/**
 * This file was generated by apps/server/scripts/run-db-codegen.ts.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface BoxAccess {
  decided_at: number | null;
  requested_at: number;
  status: string;
  user_id: string;
}

export interface BoxRemovals {
  box_id: string;
  requested_at: number;
}

export interface BoxWaitlist {
  created_at: number;
  email: string;
}

export interface BrowserDelegations {
  certificate_json: string;
  client_browser: string | null;
  client_installed: Generated<number>;
  client_platform: string | null;
  delegate_public_key: string;
  expires_at: number;
  id: string | null;
  issued_at: number;
  revoked_at: number | null;
  root_epoch: number;
  user_id: string;
}

export interface DaemonLinkClaims {
  approval_json: string | null;
  approved_at: number | null;
  attempt_count: number;
  box_id: string | null;
  claim_commitment: string;
  created_at: number;
  expires_at: number;
  link_claim_id: string | null;
  poll_token_hash: string;
  public_claim_json: string;
  server_nonce: string;
  state: string;
  user_id: string;
}

export interface Daemons {
  box_id: string | null;
  daemon_binding_json: string;
  daemon_identity_key_commitment: string;
  daemon_identity_p256_public_key: string;
  daemon_identity_public_key: string;
  id: string | null;
  identity_seal_backend: string;
  last_seen: number | null;
  name: string;
  platform: string;
  user_id: string;
  version: string | null;
}

export interface DelegationRevocationOutbox {
  acknowledged_at: number | null;
  actor_certificate_json: string;
  command_id: string;
  created_at: number;
  daemon_id: string;
  rejected_reason: string | null;
  revocation_json: string;
  revocation_nonce: string;
  sequence: Generated<number | null>;
  user_id: string;
}

export interface DelegationRevocations {
  actor_certificate_json: string;
  actor_delegation_id: string;
  created_at: number;
  nonce: string | null;
  revocation_json: string;
  revoked_count: number;
  user_id: string;
}

export interface KeyboardSettings {
  settings_json: string;
  updated_at: number;
  user_id: string | null;
}

export interface LinkTokens {
  box_id: string | null;
  expires_at: number;
  token_hash: string | null;
  used_at: number | null;
  user_id: string;
}

export interface NotificationOutbox {
  id: string;
  kind: string;
  payload: string;
  user_id: string;
}

export interface PushSubscriptions {
  auth: string;
  endpoint: string;
  id: string | null;
  p256dh: string;
  user_id: string;
}

export interface RefreshTokens {
  delegation_id: string;
  expires_at: number;
  family_id: string;
  id: string | null;
  rotated_at: number | null;
  token_hash: string;
  user_id: string;
}

export interface Users {
  created_at: number;
  deletion_scheduled_at: number | null;
  id: string | null;
  opaque_registration_record: string;
  privileged_at: number | null;
  root_envelope_ciphertext: string;
  root_envelope_nonce: string;
  root_epoch: number;
  root_key_commitment: string;
  root_public_key: string;
  suspended_at: number | null;
  username: string;
}

export interface DB {
  box_access: BoxAccess;
  box_removals: BoxRemovals;
  box_waitlist: BoxWaitlist;
  browser_delegations: BrowserDelegations;
  daemon_link_claims: DaemonLinkClaims;
  daemons: Daemons;
  delegation_revocation_outbox: DelegationRevocationOutbox;
  delegation_revocations: DelegationRevocations;
  keyboard_settings: KeyboardSettings;
  link_tokens: LinkTokens;
  notification_outbox: NotificationOutbox;
  push_subscriptions: PushSubscriptions;
  refresh_tokens: RefreshTokens;
  users: Users;
}
