# Generated by //tools/bazel/bun:generate_graph.py; do not edit.
load("@aspect_rules_js//js:defs.bzl", "js_library")

def declare_conformance_sources():
    js_library(name = "conformance_dependencies", deps = ["//:js_configuration"])
    js_library(name = "conformance_sources", srcs = ["conformance.test.ts"], deps = [":conformance_dependencies"])
