import { beforeAll, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import * as graphics from './pkg/graphics_wasm.js';

// Generated by tile-codec-bench --vector from a 1x1 straight-alpha RGBA source.
// The native encoder contributes the two gutters, producing a 3x3 PNG.
const ROOT = 'af16e0cf60617f27c2bd66186e15d02dc3a2b6c7a1f22577c434585de8ff27ba';
const PNG =
  '89504e470d0a1a0a0000000d49484452000000030000000308060000005628b5bf00000032494441547801012700d8ff021b51f37f1b51f37f1b51f37f0200000000000000000000000002000000000000000000000000b41b05a164a468ee0000000049454e44ae426082';
const png = Uint8Array.from(Buffer.from(PNG, 'hex'));
const root = Uint8Array.from(Buffer.from(ROOT, 'hex'));
let memory: WebAssembly.Memory;

beforeAll(async () => {
  memory = graphics.initSync({
    module: new Uint8Array(await readFile(new URL('./pkg/graphics_wasm_bg.wasm', import.meta.url))),
  }).memory;
});

test('native tile commitment verifies over every split with fixed WASM scratch', () => {
  const owner = new graphics.GraphicsAssets();
  try {
    const inputPtr = owner.input_ptr();
    const rootPtr = owner.root_ptr();
    const update = (bytes: Uint8Array): boolean => {
      new Uint8Array(memory.buffer, inputPtr, bytes.length).set(bytes);
      return owner.update(bytes.length);
    };
    new Uint8Array(memory.buffer, rootPtr, 32).set(root);
    expect(owner.input_capacity()).toBe(16_384);
    const size = memory.buffer.byteLength;
    for (let split = 1; split < png.length; split += 1) {
      expect(owner.begin(png.length, 3, 3)).toBe(true);
      expect(update(png.subarray(0, split))).toBe(true);
      expect(update(png.subarray(split))).toBe(true);
      expect(owner.finish()).toBe(true);
      expect(owner.finish()).toBe(false);
    }
    expect(memory.buffer.byteLength).toBe(size);
    // Unrelated owners/growth may detach every JS view, but offsets stay stable.
    expect(owner.begin(png.length, 3, 3)).toBe(true);
    expect(update(png.subarray(0, 41))).toBe(true);
    memory.grow(1);
    expect(owner.input_ptr()).toBe(inputPtr);
    expect(owner.root_ptr()).toBe(rootPtr);
    expect(update(png.subarray(41))).toBe(true);
    expect(owner.finish()).toBe(true);
  } finally {
    owner.free();
  }
});

test('corruption, wrong shape, truncation and bad updates revoke the pending object', () => {
  const owner = new graphics.GraphicsAssets();
  try {
    new Uint8Array(memory.buffer, owner.root_ptr(), 32).set(root);
    const update = (bytes: Uint8Array): boolean => {
      new Uint8Array(memory.buffer, owner.input_ptr(), bytes.length).set(bytes);
      return owner.update(bytes.length);
    };
    for (let i = 0; i < png.length; i += 1) {
      const corrupt = png.slice();
      corrupt[i] = (corrupt[i] ?? 0) ^ 1;
      expect(owner.begin(png.length, 3, 3)).toBe(true);
      expect(update(corrupt)).toBe(true);
      expect(owner.finish()).toBe(false);
    }
    for (const [width, height] of [
      [4, 3],
      [3, 4],
    ] as const) {
      expect(owner.begin(png.length, width, height)).toBe(true);
      expect(update(png)).toBe(true);
      expect(owner.finish()).toBe(false);
    }
    for (const length of [0, 16_385, 0xffff_ffff]) {
      expect(owner.begin(png.length, 3, 3)).toBe(true);
      expect(owner.update(length)).toBe(false);
      expect(update(png)).toBe(false);
      expect(owner.finish()).toBe(false);
    }
    expect(owner.begin(png.length, 3, 3)).toBe(true);
    expect(update(png.subarray(0, png.length - 1))).toBe(true);
    expect(owner.finish()).toBe(false);
    expect(owner.begin(png.length, 3, 3)).toBe(true);
    expect(update(png)).toBe(true);
    expect(owner.begin(png.length, 65_539, 3)).toBe(false);
    expect(owner.finish()).toBe(false);
  } finally {
    owner.free();
  }
});

// Pinned by merkur-graphics/tests/animation.rs. The independent wire construction
// below also catches field offsets, endianness and domain-separation drift.
const ANIMATION_ROOT = Uint8Array.from(
  Buffer.from('bf7be3ae142f2c0a0521012ec78f50c15cfd9affff98e809316d1d9d01ad5b03', 'hex'),
);
function animationManifest(): Uint8Array {
  const bytes = new Uint8Array(64 + 3 * 36);
  const view = new DataView(bytes.buffer);
  view.setUint32(0, 2);
  view.setUint32(4, 3);
  view.setUint32(8, 3);
  view.setUint32(12, 3);
  view.setBigUint64(16, 7n);
  view.setBigUint64(24, 100_000n);
  for (const [i, gap] of [0, 40, 25].entries()) {
    bytes.fill(i, 64 + i * 36, 96 + i * 36);
    view.setUint32(96 + i * 36, gap);
  }
  return bytes;
}

test('animation commitment rejects every corrupted byte, truncated prefix and wrong canvas', () => {
  const owner = new graphics.GraphicsAssets();
  const bytes = animationManifest();
  const update = (part: Uint8Array) => {
    new Uint8Array(memory.buffer, owner.input_ptr(), part.length).set(part);
    return owner.update(part.length);
  };
  try {
    new Uint8Array(memory.buffer, owner.root_ptr(), 32).set(ANIMATION_ROOT);
    for (let split = 1; split < bytes.length; split++) {
      expect(owner.begin_manifest(bytes.length, 2, 3)).toBe(true);
      expect(update(bytes.subarray(0, split))).toBe(true);
      expect(update(bytes.subarray(split))).toBe(true);
      expect(owner.finish()).toBe(true);
      expect(owner.finish()).toBe(false);
      const corrupt = bytes.slice();
      corrupt[split] = (corrupt[split] ?? 0) ^ 1;
      expect(owner.begin_manifest(bytes.length, 2, 3)).toBe(true);
      expect(update(corrupt)).toBe(true);
      expect(owner.finish()).toBe(false);
      expect(owner.begin_manifest(bytes.length, 2, 3)).toBe(true);
      expect(update(bytes.subarray(0, split))).toBe(true);
      expect(owner.finish()).toBe(false);
    }
    expect(owner.begin_manifest(bytes.length, 3, 2)).toBe(true);
    expect(update(bytes)).toBe(true);
    expect(owner.finish()).toBe(false);
    expect(owner.begin_manifest(147_521, 2, 3)).toBe(false);
    expect(owner.begin_manifest(bytes.length, 16385, 1)).toBe(false);
    expect(owner.begin_manifest(bytes.length, 2, 3)).toBe(true);
    expect(owner.update(16_385)).toBe(false);
    expect(owner.finish()).toBe(false);
  } finally {
    owner.free();
  }
});

test('terminal WASM samples the verified native manifest without tick history', async () => {
  const term = await import('../term-wasm/pkg/term_wasm.js');
  term.initSync({
    module: new Uint8Array(
      await readFile(new URL('../term-wasm/pkg/term_wasm_bg.wasm', import.meta.url)),
    ),
  });
  const bytes = animationManifest();
  const timeline = term.GraphicsAnimation.parse(bytes, ANIMATION_ROOT, 2, 3);
  if (timeline === undefined) throw new Error('valid native manifest rejected');
  try {
    for (const [now, frame, next] of [
      [0, 1, 140_000],
      [139_999, 1, 140_000],
      [140_000, 2, 165_000],
      [165_000, 1, 205_000],
      [6_500_140_000, 2, 6_500_165_000],
    ]) {
      expect(timeline.sample(now ?? 0)).toBe(frame ?? 0);
      expect(timeline.next_us()).toBe(next ?? 0);
    }
    expect(timeline.sample(Number.NaN)).toBe(2);
    expect(term.GraphicsAnimation.parse(bytes, new Uint8Array(32), 2, 3)).toBeUndefined();
    expect(term.GraphicsAnimation.parse(bytes, ANIMATION_ROOT, 3, 2)).toBeUndefined();
  } finally {
    timeline.free();
  }
});
