#!/usr/bin/env python3
"""Translate locked Cargo metadata into native rules_rust declarations.

Refresh is an explicit metadata operation; ordinary checking never runs Cargo or
modifies a lockfile. Compiler roots come only from the exact retained Cargo unit graph; aggregate
metadata features are never assigned to compiler targets.
"""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import importlib.util


ROOT = Path(__file__).resolve().parents[3]
HERE = ROOT / "tools/bazel/rust"
HEADER = "# Generated by tools/bazel/rust/generate.py. DO NOT EDIT.\n"


def literal(value):
    return json.dumps(value, sort_keys=True)


def relative(path):
    return str(Path(path).relative_to(ROOT))


def metadata(sdk):
    import tomllib
    version = tomllib.loads((ROOT / "rust-toolchain.toml").read_text())["toolchain"]["channel"]
    sdk.require_locks([ROOT / "Cargo.lock"])
    result = subprocess.run(
        sdk.command("cargo", version) + ["metadata", "--offline", "--locked", "--format-version=1"],
        cwd=ROOT, env=sdk.environment(), check=True, capture_output=True, text=True,
    )
    return json.loads(result.stdout)


def snapshot(raw):
    import tomllib
    workspace_lints = tomllib.loads((ROOT / "Cargo.toml").read_text()).get("workspace", {}).get("lints", {})
    ids = {}
    packages = []
    for package in raw["packages"]:
        if package["source"] is None:
            ids[package["id"]] = "workspace:" + relative(Path(package["manifest_path"]).parent)
        else:
            ids[package["id"]] = package["id"]
    for package in sorted(raw["packages"], key=lambda p: ids[p["id"]]):
        p = {k: package[k] for k in ["name", "version", "source", "edition", "features"]}
        p["id"] = ids[package["id"]]
        if package["source"] is None:
            manifest = tomllib.loads(Path(package["manifest_path"]).read_text())
            declared_lints = manifest.get("lints", {})
            p["lints"] = workspace_lints if declared_lints.get("workspace") else declared_lints
            p["manifest"] = relative(package["manifest_path"])
            p["targets"] = [
                {**{k: t[k] for k in ["name", "kind", "crate_types", "edition", "test", "doctest"]},
                 "source": relative(t["src_path"]),
                 "required_features": t.get("required-features", [])}
                for t in package["targets"]
            ]
            p["dependencies"] = [
                {**{k: d[k] for k in ["name", "rename", "kind", "optional", "target", "uses_default_features", "features"]},
                 "path": relative(d["path"]) if d.get("path") else None}
                for d in package["dependencies"]
            ]
        packages.append(p)
    nodes = [
        {"id": ids[node["id"]], "features": node["features"],
         "deps": [{**dep, "pkg": ids[dep["pkg"]]} for dep in node["deps"]]}
        for node in sorted(raw["resolve"]["nodes"], key=lambda n: ids[n["id"]])
    ]
    inputs = ["Cargo.toml", "Cargo.lock", "rust-toolchain.toml", ".cargo/config.toml"]
    inputs += [p["manifest"] for p in packages if p["source"] is None]
    return {
        "inputs": {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in sorted(set(inputs))},
        "members": sorted(ids[p] for p in raw["workspace_members"]),
        "packages": packages,
        "nodes": nodes,
    }


def root_target(package):
    target = next((t for t in package["targets"] if "lib" in t["kind"] or "rlib" in t["kind"] or "cdylib" in t["kind"] or "proc-macro" in t["kind"]), None)
    return target["name"].replace("-", "_") if target else None


def render_package(package, graph):
    """Expose native roots from configured units, never metadata feature unions."""
    result = render_patch_sources(package)
    result = result.replace(HEADER, HEADER + 'load("//tools/bazel/rust:package_targets.bzl", "declare_rust_package")\n', 1)
    path = str(Path(package["manifest"]).parent)
    result += "\ndeclare_rust_package(" + literal(package["name"]) + ")\n"
    if path in ["packages/e2e-wasm", "packages/graphics-wasm"]:
        result = result.replace(HEADER, HEADER + 'load(":bun_tests.bzl", "declare_bun_tests")\n', 1)
        result += "\ndeclare_bun_tests()\n"
    if path in ["packages/graphics-codec-probe", "packages/term-wasm"]:
        result = result.replace(HEADER, HEADER + 'load(":wasm_artifacts.bzl", "declare_wasm_artifacts")\n', 1)
        result += "\ndeclare_wasm_artifacts()\n"
    if path == "packages/merkur-client-native":
        result = result.replace(HEADER, HEADER + 'load(":browser_oracle.bzl", "declare_browser_registration_oracle")\n', 1)
        result += "\ndeclare_browser_registration_oracle()\n"
    return result


def render_patch_sources(package):
    hidden = {"e2e-wasm": [".cargo/config.toml"], "term-wasm": [".cargo/config.toml"], "alacritty_terminal": [".cargo-ok", ".cargo_vcs_info.json"]}.get(package["name"], [])
    lints = package.get("lints", {})
    check_cfg = {"test": []}
    for options in lints.get("rust", {}).values():
        if isinstance(options, dict):
            for predicate in options.get("check-cfg", []):
                if not predicate.startswith("cfg(") or not predicate.endswith(")") or not predicate[4:-1].isidentifier():
                    raise ValueError("unmodeled vendored check-cfg predicate: " + predicate)
                check_cfg[predicate[4:-1]] = []
    body = HEADER + 'load("@rules_rust//rust:defs.bzl", "rust_lint_config")\npackage(default_visibility = ["//visibility:public"])\nexports_files(["Cargo.toml"])\nexports_files(glob(["**/*.rs"], exclude = ["target/**"]))\nfilegroup(name = "rust_sources", srcs = glob(["**/*.rs"], exclude = ["target/**"]))\nfilegroup(name = "package_data", srcs = glob(["**"], exclude = ["BUILD.bazel", "Cargo.lock", "node_modules/**", "target/**", "dist/**", "pkg/**", "test-results/**", ".*", "**/.*", ".*/**", "**/.*/**", "__pycache__/**", "**/__pycache__/**", "*.pyc", "**/*.pyc", ".env", ".env.*", "**/.env", "**/.env.*", ".bazelrc.local", "**/.bazelrc.local"]))\nfilegroup(name = "verification_inputs", srcs = glob(["**"], exclude = ["node_modules/**", "target/**", "dist/**", "pkg/**", "test-results/**", ".*", "**/.*", ".*/**", "**/.*/**", "__pycache__/**", "**/__pycache__/**", "*.pyc", "**/*.pyc", ".git/**", ".codegraph/**", ".tools/**", ".cache/**", "coverage/**", ".vite/**", ".env", ".env.*", "**/.env", "**/.env.*", ".bazelrc.local", "**/.bazelrc.local", ".DS_Store", "**/.DS_Store"]))\nrust_lint_config(\n    name = "manifest_lints",\n    rustc = ' + literal({name: value["level"] if isinstance(value, dict) else value for name, value in lints.get("rust", {}).items()}) + ',\n    clippy = ' + literal(lints.get("clippy", {})) + ',\n    rustdoc = ' + literal(lints.get("rustdoc", {})) + ',\n    rustc_check_cfg = ' + literal(check_cfg) + ',\n)\n'

    body = body.replace('".DS_Store", "**/.DS_Store"]))\nrust_lint_config(', '".DS_Store", "**/.DS_Store"]) + ' + literal(hidden) + ')\nrust_lint_config(')
    if hidden:
        body += "exports_files(" + literal(hidden) + ")\n"
    return body


def main():
    global ROOT, HERE
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true")
    parser.add_argument("--sdk-descriptor", type=Path)
    parser.add_argument("--source-root", type=Path)
    args = parser.parse_args()
    sdk = None
    if args.refresh:
        if args.sdk_descriptor is None or args.source_root is None:
            parser.error("--refresh requires --sdk-descriptor and --source-root; ambient acquisition tools are forbidden")
        ROOT = args.source_root.resolve(strict=True)
        HERE = ROOT / "tools/bazel/rust"
        resolver_path = Path(__file__).with_name("acquisition_sdk.py")
        spec = importlib.util.spec_from_file_location("declared_sdk", resolver_path)
        if spec is None or spec.loader is None:
            raise ValueError("missing declared native acquisition SDK resolver File")
        resolver = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(resolver)
        sdk = resolver.NativeCargoSdk.load(args.sdk_descriptor)
    snapshot_file = HERE / "metadata.json"
    if args.refresh:
        try:
            graph = snapshot(metadata(sdk))
        finally:
            sdk.close()
        snapshot_file.write_text(json.dumps(graph, indent=2, sort_keys=True) + "\n")
    else:
        graph = json.loads(snapshot_file.read_text())
    stale = []
    for path, digest in graph["inputs"].items():
        if not (ROOT / path).exists() or hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != digest:
            stale.append(path)
    outputs = {}
    for package in graph["packages"]:
        if package["source"] is not None:
            continue
        path = Path(package["manifest"]).parent / "BUILD.bazel"
        outputs[path] = render_package(package, graph) if package["id"] in graph["members"] else render_patch_sources(package)
        outputs[path] = outputs[path].replace(
            HEADER,
            HEADER + 'load("//tools/bazel/bun:runtime_sources.bzl", "declare_runtime_sources")\n',
            1,
        ) + "\ndeclare_runtime_sources()\n"
    for path, body in outputs.items():
        output = ROOT / path
        if args.refresh:
            output.write_text(body)
        elif not output.exists() or output.read_text() != body:
            stale.append(str(path))
    if stale:
        sys.stderr.write("Stale Rust graph inputs/declarations: " + ", ".join(stale) + "\n")
        return 1
    print(f"Rust graph checked: {len(outputs)} first-party packages, {len(graph['packages'])} locked packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
