#!/usr/bin/env python3
"""Emit Bazel source packages from the exact original Rolldown archive.

The repository rule applies the declared patch. This inventory retains every
original regular source File, including hidden Cargo configuration, and derives
lint ordering from the original TOML rather than a second hand-authored policy.
"""
import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import tarfile
import tomllib


def lint_configuration(manifest, workspace):
    lints = manifest.get("lints", {})
    if lints.get("workspace") is True:
        if set(lints) != {"workspace"}:
            raise ValueError("mixed Rolldown local and workspace lints")
        lints = workspace.get("lints", {})
    result = {}
    for category in ["rust", "clippy", "rustdoc"]:
        entries = lints.get(category, {})
        ordered = sorted(entries.items(), key=lambda item: (
            item[1].get("priority", 0) if isinstance(item[1], dict) else 0,
            item[0],
        ))
        result["rustc" if category == "rust" else category] = {
            name: value["level"] if isinstance(value, dict) else value
            for name, value in ordered
        }
    return result


def source_packages(archive, original):
    if hashlib.sha256(archive.read_bytes()).hexdigest() != original["archive_sha256"]:
        raise ValueError("Rolldown source archive differs from its original commit")
    prefix = "rolldown-" + original["commit"] + "/"
    files, manifests = {}, {}
    with tarfile.open(archive, "r:gz") as source:
        for member in source:
            if not member.isfile():
                continue
            if not member.name.startswith(prefix):
                raise ValueError("Rolldown File lies outside the original archive root")
            name = member.name.removeprefix(prefix)
            path = PurePosixPath(name)
            if path.is_absolute() or ".." in path.parts or name in files:
                raise ValueError("noncanonical or duplicate Rolldown source File")
            files[name] = member
            if path.name == "Cargo.toml":
                stream = source.extractfile(member)
                if stream is None:
                    raise ValueError("missing original Cargo manifest File")
                manifests[str(path.parent) if str(path.parent) != "." else ""] = tomllib.loads(stream.read().decode())
    workspace = manifests[""]["workspace"]
    packages = {name: {"files": [], "lints": lint_configuration(manifest, workspace)}
                for name, manifest in sorted(manifests.items())}
    for name in sorted(files):
        owners = [package for package in packages if not package or name.startswith(package + "/")]
        owner = max(owners, key=len)
        packages[owner]["files"].append(name[len(owner) + 1:] if owner else name)
    return packages


def render(packages):
    return ("# Generated by tools/bazel/rust/rolldown_source.py from the pinned original archive.\n"
            "ROLLDOWN_SOURCE_PACKAGES = " + json.dumps(packages, indent=4) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--source-instances", type=Path, required=True)
    parser.add_argument("--source-instance", required=True)
    args = parser.parse_args()
    original = json.loads(args.source_instances.read_text())[args.source_instance]
    args.output.write_text(render(source_packages(args.archive, original)))


if __name__ == "__main__":
    main()
