"""Exact patched Rolldown source repository and existing SDK File inventory."""
load("//tools/bazel/bun:rolldown-js-dependencies.bzl", "rolldown_js_dependencies")

_INVENTORY_HEADER = "# Generated by tools/bazel/rust/rolldown_source.py from the pinned original archive.\nROLLDOWN_SOURCE_PACKAGES = "

def _source_packages(importers, original_packages):
    packages = {}
    files = []
    for package, configuration in original_packages.items():
        packages[package] = {"files": [], "lints": configuration["lints"]}
        files.extend([(package + "/" if package else "") + file for file in configuration["files"]])
    for importer in importers:
        if importer not in packages:
            packages[importer] = {"files": [], "lints": {}}
    for logical in sorted(files):
        owner = ""
        prefix = ""
        for component in logical.split("/")[:-1]:
            prefix = (prefix + "/" if prefix else "") + component
            if prefix in packages:
                owner = prefix
        packages[owner]["files"].append(logical[len(owner) + 1:] if owner else logical)
    return packages

def _source_impl(ctx):
    original = json.decode(ctx.read(ctx.attr.source_instances))[ctx.attr.source_instance]
    inventory = ctx.read(ctx.attr.source_inventory)
    if not inventory.startswith(_INVENTORY_HEADER):
        fail("Rolldown source inventory must be generated from its original archive")
    original_packages = json.decode(inventory[len(_INVENTORY_HEADER):])
    ctx.download_and_extract(
        url = "https://github.com/rolldown/rolldown/archive/" + original["commit"] + ".tar.gz",
        sha256 = original["archive_sha256"],
        stripPrefix = "rolldown-" + original["commit"],
    )
    if not ctx.attr.patches:
        fail("Rolldown source requires its ordered native source patches")
    for patch in ctx.attr.patches:
        ctx.patch(ctx.path(patch), strip = 1)
    importers = rolldown_js_dependencies(ctx)
    source_labels = []
    packages = _source_packages(importers, original_packages)
    for package in sorted(packages):
        configuration = packages[package]
        files = configuration["files"]
        body = 'load("@rules_rust//rust:defs.bzl", "rust_lint_config")\n'
        if package in importers:
            body += importers[package].preamble
        body += 'package(default_visibility = ["//visibility:public"])\n'
        body += "exports_files(" + repr(files) + ")\n"
        body += 'filegroup(name = "rust_sources", srcs = ' + repr([file for file in files if file.endswith(".rs")]) + ")\n"
        body += 'filegroup(name = "package_data", srcs = ' + repr(files) + ")\n"
        body += 'rust_lint_config(name = "manifest_lints"'
        for category, lints in configuration["lints"].items():
            body += ", " + category + " = " + repr(lints)
        body += ")\n"
        if not package:
            body += 'exports_files(["sources.bzl"])\n'
        if package in importers:
            body += importers[package].body
        ctx.file((package + "/" if package else "") + "BUILD.bazel", body)
        for file in files:
            logical = (package + "/" if package else "") + file
            source_labels.append('    Label(' + repr("//" + package + ":" + file) + '): ' + repr(logical) + ',\n')
    ctx.file("sources.bzl", "ROLLDOWN_SOURCE_FILES = {\n" + "".join(source_labels) + "}\n")

rolldown_source_repository = repository_rule(
    implementation = _source_impl,
    attrs = {
        "patches": attr.label_list(allow_files = True, mandatory = True),
        "source_instances": attr.label(allow_single_file = True, mandatory = True),
        "source_instance": attr.string(mandatory = True),
        "source_inventory": attr.label(allow_single_file = True, mandatory = True),
        "npm_repository": attr.string(mandatory = True),
        "yq": attr.label_keyed_string_dict(allow_files = True, mandatory = True),
    },
)
