#!/usr/bin/env python3
"""Capture CargoShear's all-features metadata; Cargo never compiles product code."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "tools/bazel/rust/shear"
AUTHORITY = OUTPUT / "snapshot.json"
SOURCE_GROUPS = ROOT / "tools/bazel/rust/shear_inputs.bzl"


def source_groups(authority):
    labels = sorted({"//" + item["manifest"].removesuffix("/Cargo.toml") + ":package_data"
                     for item in authority["local_packages"]})
    return "# @generated by shear_snapshot.py; exact locked local package source roots.\nSHEAR_SOURCE_GROUPS = " + json.dumps(labels) + "\n"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path, value):
    path.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")


def check():
    authority = json.loads(AUTHORITY.read_text())
    if authority["command"] != ["metadata", "--offline", "--locked", "--all-features", "--format-version=1"]:
        raise ValueError("CargoShear metadata has another resolver command")
    for member, expected in authority["inputs"].items():
        if digest(ROOT / member) != expected:
            raise ValueError("Stale CargoShear resolution input: " + member)
    manifest = tomllib.loads((ROOT / "Cargo.toml").read_text())
    members = manifest["workspace"]["members"]
    if any(any(character in member for character in "*?[") for member in members):
        raise ValueError("Workspace membership needs explicit Cargo glob expansion")
    package_manifests = {member + "/Cargo.toml" for member in members}
    for source in manifest.get("patch", {}).values():
        for package in source.values():
            if "path" in package:
                package_manifests.add(package["path"] + "/Cargo.toml")
    if package_manifests != {package["manifest"] for package in authority["local_packages"]}:
        raise ValueError("CargoShear local package membership differs from workspace/patch declarations")
    required = {"Cargo.toml", "Cargo.lock", "rust-toolchain.toml", ".cargo/config.toml"} | package_manifests
    if set(authority["inputs"]) != required:
        raise ValueError("CargoShear snapshot input membership differs")
    for member, expected in authority["parts"].items():
        if digest(OUTPUT / member) != expected:
            raise ValueError("Changed CargoShear metadata part: " + member)
    if set(authority["parts"]) != {p.name for p in OUTPUT.glob("*.json") if p != AUTHORITY}:
        raise ValueError("CargoShear metadata part inventory differs")
    if SOURCE_GROUPS.read_text() != source_groups(authority):
        raise ValueError("CargoShear declared local source groups differ")


def capture(cargo, rustc, cargo_home, biome):
    cargo = Path(cargo).resolve(strict=True)
    rustc = Path(rustc).resolve(strict=True)
    environment = {"PATH": "", "HOME": str(cargo_home), "CARGO_HOME": str(cargo_home),
                   "RUSTC": str(rustc), "CARGO_NET_OFFLINE": "true", "LANG": "C", "LC_ALL": "C"}
    def configuration():
        for name in ["config", "config.toml"]:
            if (cargo_home / name).exists():
                raise ValueError("Undeclared Cargo-home configuration")
        for directory in [ROOT, *ROOT.parents]:
            for name in ["config", "config.toml"]:
                candidate = directory / ".cargo" / name
                if candidate == ROOT / ".cargo/config.toml":
                    continue
                if candidate.exists():
                    raise ValueError("Undeclared ancestor Cargo configuration")
    def run(executable, arguments):
        configuration()
        output = subprocess.check_output([str(executable), *arguments], cwd=ROOT, env=environment, text=True)
        configuration()
        return output
    cargo_identity = run(cargo, ["--version"]).strip()
    rustc_identity = run(rustc, ["-vV"]).strip()
    if not cargo_identity.startswith("cargo 1.97.1 ") or not rustc_identity.startswith("rustc 1.97.1 "):
        raise ValueError("CargoShear capture requires pinned Cargo/rustc 1.97.1")
    command = ["metadata", "--offline", "--locked", "--all-features", "--format-version=1"]
    metadata = json.loads(run(cargo, command))
    local = []
    for package in metadata["packages"]:
        if package["source"] is None:
            manifest = str(Path(package["manifest_path"]).relative_to(ROOT))
            local.append({"id": package["id"].replace(str(ROOT), "@workspace@"), "name": package["name"], "manifest": manifest})
    def normalize(value):
        if isinstance(value, str):
            value = value.replace(str(ROOT), "@workspace@")
            prefix = str(cargo_home / "registry/src") + "/"
            if prefix in value:
                before, member = value.split(prefix, 1)
                value = before + "@registry@/" + member.split("/", 1)[1]
            return value
        if isinstance(value, list):
            return [normalize(item) for item in value]
        if isinstance(value, dict):
            return {key: normalize(item) for key, item in value.items()}
        return value
    metadata = normalize(metadata)
    OUTPUT.mkdir(exist_ok=True)
    packages = metadata.pop("packages")
    write(OUTPUT / "core.json", metadata)
    part_names = {"core.json"}
    for index in range(0, len(packages), 40):
        name = "packages-%03d.json" % (index // 40)
        part_names.add(name)
        write(OUTPUT / name, packages[index:index + 40])
    for previous in OUTPUT.glob("packages-*.json"):
        if previous.name not in part_names:
            previous.unlink()
    biome = Path(biome).resolve(strict=True)
    if not run(biome, ["--version"]).strip().endswith("2.5.10"):
        raise ValueError("Metadata formatting requires pinned Biome 2.5.10")
    subprocess.run([str(biome), "format", "--write", *[str(OUTPUT / name) for name in sorted(part_names)]],
                   cwd=ROOT, env=environment, check=True, stdout=subprocess.DEVNULL)
    inputs = {"Cargo.toml", "Cargo.lock", "rust-toolchain.toml", ".cargo/config.toml"}
    inputs.update(item["manifest"] for item in local)
    write(AUTHORITY, {
        "command": command,
        "cargo_identity": cargo_identity, "rustc_identity": rustc_identity,
        "cargo_sha256": digest(cargo), "rustc_sha256": digest(rustc),
        "inputs": {member: digest(ROOT / member) for member in sorted(inputs)},
        "local_packages": sorted(local, key=lambda item: item["manifest"]),
        "workspace_members": metadata["workspace_members"],
        "parts": {part.name: digest(part) for part in sorted(OUTPUT.glob("*.json")) if part != AUTHORITY},
    })
    subprocess.run([str(biome), "format", "--write", str(AUTHORITY)],
                   cwd=ROOT, env=environment, check=True, stdout=subprocess.DEVNULL)
    SOURCE_GROUPS.write_text(source_groups(json.loads(AUTHORITY.read_text())))
    check()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--cargo")
    parser.add_argument("--rustc")
    parser.add_argument("--cargo-home", type=Path)
    parser.add_argument("--biome")
    args = parser.parse_args()
    if args.check:
        check()
    elif args.cargo and args.rustc and args.cargo_home and args.biome:
        capture(args.cargo, args.rustc, args.cargo_home.resolve(strict=True), args.biome)
    else:
        parser.error("capture requires explicit cargo, rustc, cargo-home and biome paths")


if __name__ == "__main__":
    main()
