#!/usr/bin/env python3
"""Emit shared native Rust units from Cargo's exact, locked unit graph oracle.

Cargo is not invoked here. Every compiler unit has an explicit source, profile,
host/target, feature set and dependency context. Equal recursive contexts share
one Bazel label; unrelated build roots never unify their features.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys
import tomllib

import configured_parity
import license_metadata
import native_receipts

ROOT = Path(__file__).resolve().parents[3]
HERE = ROOT / "tools/bazel/rust"
DEST = HERE / "units"
HEADER = "# Generated by tools/bazel/rust/units.py. DO NOT EDIT.\n"


def text(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False)


def starlark(value):
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, list):
        return "[" + ", ".join(starlark(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(text(name) + ": " + starlark(item) for name, item in sorted(value.items())) + "}"
    return text(value)


def key(value):
    return hashlib.sha256(text(value).encode()).hexdigest()


def identifier(value):
    return value.replace(":", "_").replace("-", "_").replace(".", "_").replace("+", "_")


def custom_cfg_env(rust_flags):
    """Cargo exposes every explicitly declared rustc cfg to build scripts.

    rules_rust supplies built-in target cfgs separately. Its pinned runner does
    not forward custom --cfg declarations, so retain those exact declarations
    as part of the build-script action environment.
    """
    values = {}
    index = 0
    while index < len(rust_flags):
        flag = rust_flags[index]
        if flag == "--cfg":
            index += 1
            if index == len(rust_flags):
                raise ValueError("missing rustc cfg declaration")
            declaration = rust_flags[index]
        elif flag.startswith("--cfg="):
            declaration = flag.removeprefix("--cfg=")
        else:
            index += 1
            continue
        name, separator, value = declaration.partition("=")
        if not name.isidentifier() or not name.isascii():
            raise ValueError("unmodeled rustc cfg identifier: " + name)
        decoded = json.loads(value) if separator else None
        if decoded is not None and not isinstance(decoded, str):
            raise ValueError("rustc cfg values must be strings")
        entry = values.setdefault("CARGO_CFG_" + name.upper(), [])
        if decoded is not None and decoded not in entry:
            entry.append(decoded)
        index += 1
    return {name: ",".join(items) for name, items in values.items()}


def flags(profile):
    result = ["-Copt-level=" + profile["opt_level"], "-Cdebuginfo=" + str(profile["debuginfo"]), "-Cdebug-assertions=" + ("yes" if profile["debug_assertions"] else "no"), "-Coverflow-checks=" + ("yes" if profile["overflow_checks"] else "no")]
    # Cargo1.97.1 emits panic only for non-Unwind profile strategies.
    # Leaving Unwind implicit preserves target defaults (WASM abort).
    if profile["panic"] != "unwind":
        result.append("-Cpanic=" + profile["panic"])
    if profile["codegen_units"] is not None:
        result.append("-Ccodegen-units=" + str(profile["codegen_units"]))
    if profile.get("split_debuginfo") is not None:
        result.append("-Csplit-debuginfo=" + profile["split_debuginfo"])
    if profile["lto"] not in ["false", "off"]:
        result.append("-Clto=" + profile["lto"])
    if profile["rpath"]:
        result.append("-Crpath=yes")
    strip = profile.get("strip", {})
    if "resolved" in strip and strip["resolved"] != "None":
        result.append("-Cstrip=" + strip["resolved"]["Named"])
    if profile.get("codegen_backend") is not None:
        raise ValueError("unmodeled codegen backend")
    return result


def collect(documents, native_documents=()):
    configured_parity.validate_documents(
        [json.loads(path.read_text()) for path in documents],
        [json.loads(path.read_text()) for path in native_documents],
    )
    nodes, roots, packages = {}, {}, {}
    replacements = set()
    for filename in native_documents:
        document = json.loads(filename.read_text())
        replacements.update((document["package"], profile, triple) for triple, profiles in document["unit_graphs"].items() for profile in profiles)
    for filename in list(documents) + list(native_documents):
        document = json.loads(filename.read_text())
        for context in document["contexts"].values():
            packages.update({package["id"]: package for package in context["packages"]})
        for triple, profiles in document["unit_graphs"].items():
            for profile, graph in profiles.items():
                if filename not in native_documents and (document["package"], profile, triple) in replacements:
                    continue
                visited, active = {}, set()
                def visit(index):
                    if index in visited:
                        return visited[index]
                    if index in active:
                        raise ValueError("cycle in Cargo compiler units")
                    active.add(index)
                    unit = graph["units"][index]
                    dependencies = [{**edge, "unit": visit(edge["index"])} for edge in unit["dependencies"]]
                    for edge in dependencies:
                        edge.pop("index")
                    identity = {**unit, "dependencies": sorted(dependencies, key=text), "execution_host": graph["execution_host"], "compiler": "1.97.1"}
                    identity["emit_cdylib"] = unit["platform"] == "wasm32-unknown-unknown" and "cdylib" in unit["target"]["crate_types"] and index in graph["roots"] and unit["mode"] == "build"
                    unit_key = key(identity)
                    nodes[unit_key] = identity
                    visited[index] = unit_key
                    active.remove(index)
                    return unit_key
                roots[f'{document["package"]}/{profile}/{triple}'] = [visit(index) for index in graph["roots"]]
    return nodes, roots, packages


def terminal_variants(nodes, roots):
    identities = {}
    instrumented_term_roots = set(roots["term-wasm/instrumented/wasm32-unknown-unknown"])
    if len(instrumented_term_roots) != 1 or any(nodes[unit_key]["pkg_id"] != "workspace:packages/term-wasm" or not nodes[unit_key]["emit_cdylib"] or nodes[unit_key]["features"] != ["pgo-train"] for unit_key in instrumented_term_roots):
        raise ValueError("training resolver must select the exact terminal pgo-train cdylib")
    for package, variant, extra_flags in [
        ("term-wasm", "instrumented", ["-Cprofile-generate=unused.profraw", "-Zno-profiler-runtime", "-Cllvm-args=-disable-vp=true"]),
        ("term-wasm", "profile_use", ["-Cprofile-use=$(location //packages/term-wasm:terminal_profile)", "-Cllvm-args=-disable-vp=true"]),
    ]:
        original_roots = sorted(instrumented_term_roots) if package == "term-wasm" and variant == "instrumented" else roots[package + "/release/wasm32-unknown-unknown"]
        visited = {}
        def visit(unit_key):
            if unit_key in visited:
                return visited[unit_key]
            original = nodes[unit_key]
            # Cargo target rustflags do not reach host build-script compilation
            # or procedural macros. Their original compiler contexts stay shared.
            if original["platform"] != "wasm32-unknown-unknown":
                return unit_key
            unit = {**original, "variant": variant, "dependencies": [{**edge, "unit": visit(edge["unit"])} for edge in original["dependencies"]], "rust_flags": original["rust_flags"] + extra_flags}
            semantic = {field: original[field] for field in ["pkg_id", "target", "profile", "rust_flags", "mode", "platform", "execution_host"]}
            semantic["features"] = [feature for feature in original["features"] if not (original["pkg_id"] == "workspace:packages/term-wasm" and feature == "pgo-train")]
            identity = (original["pkg_id"], original["target"]["name"], original["mode"])
            if identity in identities and identities[identity] != semantic:
                raise ValueError("PGO paired compiler configuration differs: " + str(identity))
            identities[identity] = semantic
            unit["semantic_metadata"] = "merkur_pgo_" + key(semantic)
            unit["compiler_env"] = {"RUSTC_BOOTSTRAP": "1"} if variant == "instrumented" else {}
            unit["profile_data"] = [] if variant == "instrumented" else ["//packages/term-wasm:terminal_profile"]
            if package == "term-wasm" and variant == "instrumented" and unit_key in instrumented_term_roots:
                unit["emit_cdylib"] = True
            result = key(unit)
            nodes[result] = unit
            visited[unit_key] = result
            return result
        roots[package + "/" + variant + "/wasm32-unknown-unknown"] = [visit(unit_key) for unit_key in original_roots]
    # Variant roots replace their acquisition-only compiler roots. Emit only
    # units owned by the final root inventory, including ordinary workspace
    # roots retained until the complete engine cutover.
    live = set()
    def retain(unit_key):
        if unit_key in live:
            return
        live.add(unit_key)
        for edge in nodes[unit_key]["dependencies"]:
            retain(edge["unit"])
    for root_ids in roots.values():
        for unit_key in root_ids:
            retain(unit_key)
    for unit_key in set(nodes) - live:
        del nodes[unit_key]


def package_facades(nodes, roots, packages):
    declarations = {}
    libraries = {}
    for package_id, package in packages.items():
        if package["source"] is None:
            libraries[package_id] = next((target["name"].replace("-", "_") for target in package["targets"] if any(kind in ["lib", "rlib", "cdylib", "proc-macro"] for kind in target["kind"])), None)
    for context, root_ids in roots.items():
        package_name, profile, triple = context.split("/")
        if package_name == "workspace-test" or profile not in ["dev", "release", "test"]:
            continue
        for unit_key in root_ids:
            unit = nodes[unit_key]
            package = packages[unit["pkg_id"]]
            name = unit["target"]["name"].replace("-", "_")
            kind, mode = unit["target"]["kind"], unit["mode"]
            if "bin" in kind and name == libraries[unit["pkg_id"]]:
                name = "bin_" + name
            if "example" in kind:
                name = "example_" + name
            elif "bench" in kind:
                name = "bench_" + name
            elif "test" in kind:
                name = "test_" + name
            elif mode == "test":
                name += "_test"
            if mode == "doctest":
                name += "_doctest"
            category = "test" if mode in ["test", "doctest"] else "build"
            if profile == "test" and category == "build":
                # Cargo's original test graph also compiles examples/helpers.
                name += "_for_tests"
            setting = ":wasm" if triple == "wasm32-unknown-unknown" else ":native_" + identifier(triple)
            if profile == "release":
                setting = ":release_wasm" if triple == "wasm32-unknown-unknown" else ":release_" + identifier(triple)
            setting = "//tools/bazel/rust/units" + setting
            target = declarations.setdefault(package_name, {}).setdefault(name, {"kind": category, "targets": {}})
            label = "//tools/bazel/rust/units:u_" + unit_key
            previous = target["targets"].get(setting)
            if previous is not None and previous != label:
                raise ValueError("ambiguous public Rust root: " + context + "/" + name)
            target["targets"][setting] = label
    body = [HEADER, 'load("//tools/bazel/rust:units.bzl", "configured_public_rust_test", "confinement_test_tags")\n\n', "_PACKAGES = " + starlark(declarations) + "\n\n", 'def declare_rust_package(package):\n    tests = []\n    for name, declaration in _PACKAGES[package].items():\n        if declaration["kind"] == "test":\n            if package == "merkur-image-worker" and name in ["test_composition", "test_descriptor", "test_encoding_allocations", "test_isolation"]:\n                configured_public_rust_test(name = name + "__darwin", binary = select(declaration["targets"]), target_compatible_with = ["@platforms//os:macos"], tags = confinement_test_tags(package, name, "aarch64-apple-darwin"))\n                configured_public_rust_test(name = name + "__linux", binary = select(declaration["targets"]), target_compatible_with = ["@platforms//os:linux"], tags = ["manual"])\n                native.alias(name = name, actual = select({"//tools/bazel/rust/units:darwin_confinement": ":" + name + "__darwin", "//conditions:default": ":" + name + "__linux"}), tags = ["manual"])\n            else:\n                configured_public_rust_test(name = name, binary = select(declaration["targets"]), tags = ["manual"])\n            tests.append(":" + name)\n        else:\n            native.alias(name = name, actual = select(declaration["targets"]), tags = ["manual"])\n    native.test_suite(name = "tests", tests = tests, tags = ["manual"])\n']
    return "".join(body)


def source_file_label(path):
    file = Path(path)
    package = file.parent
    while package != Path(".") and not (ROOT / package / "BUILD.bazel").exists():
        package = package.parent
    return "//" + ("" if package == Path(".") else str(package)) + ":" + str(file.relative_to(package))


def source_repository(package):
    return "merkur_rust_source_" + identifier(package["name"] + "_" + package["version"])


def operation_bindings(coverage, packages):
    members = set(json.loads((HERE / "metadata.json").read_text())["members"])
    owned = [package for package in packages.values() if package["id"] in members]
    policy = json.loads((HERE / "policy_crates.json").read_text())
    if policy["gate_policy_sha256"] != hashlib.sha256((ROOT / "scripts/gate-policy.ts").read_bytes()).hexdigest():
        raise ValueError("stale policy crate acquisition")
    policy_crates = policy["crates"]
    if not isinstance(policy_crates, list) or policy_crates != sorted(set(policy_crates)) or not all(isinstance(name, str) for name in policy_crates):
        raise ValueError("invalid policy crate inventory")
    if set(policy_crates) - {package["name"] for package in owned}:
        raise ValueError("policy crate has no configured compiler package")
    catalogs = {}
    for host in ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]:
        selected = [row for row in coverage if row["execution_host"] == host and row["target"] == host]
        def checks(rows):
            return [{"label": label, "kind": kind, "fresh": kind == "test"} for label, kind in sorted({(row["label"], "test" if row["operation"] in ["test", "doctest", "clippy"] else "build") for row in rows})]
        lint = checks(row for row in selected if row["operation"] == "clippy")
        tests = checks(row for row in selected if row["context"].startswith("workspace-test/"))
        crates = []
        for package in sorted(owned, key=lambda package: package["name"]):
            if package["name"] not in policy_crates:
                continue
            rows = [row for row in selected if row["owner_manifest"] == package["manifest"] and (row["context"] == package["name"] + "/test/" + host or row["operation"] == "clippy")]
            pending = ["Complete native compiler/SDK/runtime qualification"]
            if not any(row["operation"] == "clippy" for row in rows):
                pending.append("Native all-target Clippy context missing on " + host)
            if not any(row["context"] == package["name"] + "/test/" + host for row in rows):
                pending.append("Exact native owning-crate test/helper context missing on " + host)
            crates.append({"name": package["name"], "checks": checks(rows), "pending": pending})
        catalogs[host] = {"operations": [
            {"name": "build:image-worker", "checks": checks(row for row in selected if row["context"] == "merkur-image-worker/dev/" + host and row["profile"]["name"] == "dev" and row["operation"] == "build"), "pending": ["Complete native image-worker compiler/SDK/runtime qualification"] + ([] if any(row["context"] == "merkur-image-worker/dev/" + host and row["profile"]["name"] == "dev" and row["operation"] == "build" for row in selected) else ["Exact native image-worker development build context missing on " + host])},
            {"name": "rust:lint", "checks": lint, "pending": ["Complete native compiler/SDK/runtime qualification"] if lint else ["Native workspace all-target Clippy context not yet acquired on " + host]},
            {"name": "rust:test", "checks": tests, "pending": ["Exact release-profile term-wasm test root not captured", "Complete native compiler/SDK/runtime qualification"] + ([] if tests else ["Native workspace Test root missing on " + host])},
            {"name": "rust:check", "checks": checks(row for row in selected if row["context"].startswith("workspace-check/")), "pending": ["Complete native Cargo Check compiler/SDK/runtime qualification"] + ([] if any(row["context"].startswith("workspace-check/") for row in selected) else ["Exact native workspace Check root missing on " + host])},
            {"name": "rust:deps", "checks": [{"label": "//tools/bazel/rust:dependency_shear", "kind": "test", "fresh": True}], "pending": ["Native CargoShear SDK/source/runtime qualification on " + host, "Common per-test nonce/shared verdict cache admission", "Full engine command completion under current execution confinement"]},
            {"name": "test:ownership", "checks": [{"label": "//tools/ownership-proofs:" + name, "kind": "test", "fresh": True} for name in ["custody", "loom"]], "pending": ["Native diagnostic resolver/tool-SDK/runtime qualification on " + host]},
            {"name": "test:ownership:kani", "checks": [{"label": "//tools/ownership-proofs:kani", "kind": "test", "fresh": True}], "pending": ["Pinned Kani toolchain and execution-placement qualification on " + host]},
            {"name": "test:ownership:negative", "checks": [{"label": "//tools/ownership-proofs:negative_" + name, "kind": "test", "fresh": True} for name in ["custody", "route_guard", "retirement", "slot_drop", "stale_detach"]], "pending": ["Native diagnostic compiler/runtime qualification on " + host]},
        ], "crates": crates, "browserOwners": []}
    targets = {host: sorted({check["label"] for category in [catalog["operations"], catalog["crates"]] for row in category for check in row["checks"]}) for host, catalog in catalogs.items()}
    canonical = {}
    for host, labels in targets.items():
        canonical[host] = {}
        for label in labels:
            candidates = {"//tools/bazel/rust/units:u_" + row["unit"] for row in coverage if row["label"] == label and row["operation"] in ["build", "check"]}
            if len(candidates) > 1:
                raise ValueError("ambiguous catalog build alias: " + label)
            canonical[host][label] = next(iter(candidates)) if candidates else label
    return HEADER + "NATIVE_OPERATION_BINDINGS = " + starlark(catalogs) + "\nNATIVE_OPERATION_TARGETS = " + starlark(targets) + "\nNATIVE_OPERATION_CANONICAL_TARGETS = " + starlark(canonical) + "\n"


def locked_checksums(root):
    checksums = {}
    for name in ["Cargo.lock", "tools/bolero/Cargo.lock", "tools/ownership-proofs/Cargo.lock",
                 "tools/edge-kernel-profile/Cargo.lock", "tools/sim/Cargo.lock"]:
        for entry in tomllib.loads((root / name).read_text())["package"]:
            identity = entry["name"], entry["version"], entry.get("source")
            if identity in checksums and checksums[identity] != entry.get("checksum"):
                raise ValueError("independent locked source checksum disagreement")
            checksums[identity] = entry.get("checksum")
    return checksums


def source(package):
    if package["source"] is None:
        return "//" + str(Path(package["manifest"]).parent)
    return "@" + source_repository(package) + "//"


def _unit_declarations(nodes, packages, build, metadata_file, source_inputs_file, runtime_inputs_file, profile_training=None):
    if profile_training is not None and profile_training not in nodes:
        raise ValueError("Release PGO training root is absent from the captured compiler graph")
    separate = {}
    unit_source_groups = []
    inventory = json.loads(metadata_file.read_text())
    lint_members = set(inventory["members"])
    lint_manifests = {package["manifest"] for package in inventory["packages"] if package["id"] in lint_members}
    for unit_key, unit in sorted(nodes.items()):
        package = packages[unit["pkg_id"]]
        prefix = source(package)
        root = unit["target"]["src_path"]
        if package["source"] is None:
            root = str(Path(root).relative_to(Path(package["manifest"]).parent)) if Path(root).is_relative_to(Path(package["manifest"]).parent) else root
        deps, macros, aliases, macro_aliases = [], [], {}, {}
        binary_helpers = {}
        script = None
        metadata_projections = []
        metadata_declarations = []
        crate = None
        for edge in unit["dependencies"]:
            child = nodes[edge["unit"]]
            label = ":u_" + edge["unit"]
            if unit["mode"] == "doctest" and child["pkg_id"] == unit["pkg_id"] and child["target"]["src_path"] == unit["target"]["src_path"] and child["mode"] == "build":
                crate = label
            if unit["mode"] == "run-custom-build" and child["target"]["kind"] == ["custom-build"] and child["mode"] == "build":
                if script is not None:
                    raise ValueError("duplicate build-script compiler unit")
                script = label
                continue
            if unit["mode"] == "run-custom-build" and child["mode"] == "run-custom-build":
                metadata_name = "u_" + unit_key + "__links_" + str(len(metadata_projections))
                metadata_projections.append(":" + metadata_name)
                metadata_declarations.append("build_script_metadata(name = " + text(metadata_name) + ", build_script = " + text(label) + ")\n")
                continue
            if unit["mode"] == "doctest" and child["mode"] == "run-custom-build":
                continue
            if child["target"]["kind"] == ["bin"]:
                binary_helpers[child["target"]["name"]] = label
                continue
            if "proc-macro" in child["target"]["kind"]:
                macros.append(label)
            else:
                deps.append(label)
            if child["mode"] != "run-custom-build":
                (macro_aliases if "proc-macro" in child["target"]["kind"] else aliases)[label] = edge["extern_crate_name"]
        attrs = {"name": "u_" + unit_key, "crate_name": unit["target"]["name"].replace("-", "_"), "crate_root": source_file_label(unit["target"]["src_path"]) if package["source"] is None else prefix + ":" + root, "sources": prefix + ":rust_sources", "compile_data": prefix + ":package_data", "manifest": source_file_label(package["manifest"]) if package["source"] is None else prefix + ":Cargo.toml", "edition": unit["target"]["edition"], "version": package["version"], "crate_features": unit["features"], "deps": deps, "proc_macro_deps": macros, "aliases": aliases, "proc_macro_aliases": macro_aliases, "rustc_flags": flags(unit["profile"]) + ["--check-cfg=cfg(feature,values(" + ",".join(text(feature) for feature in sorted(package["features"])) + "))"], "kind": unit["target"]["kind"], "mode": unit["mode"], "platform": unit["platform"] or unit["execution_host"], "execution_host": unit["execution_host"], "first_party": package["source"] is None}
        if unit_key == profile_training:
            attrs["profile_training"] = True
        attrs["crate_types"] = unit["target"]["crate_types"]
        attrs["binary_helpers"] = binary_helpers
        attrs["lint_owned"] = package.get("manifest") in lint_manifests
        attrs["cargo_env"] = {"CARGO_PKG_NAME": package["name"], "CARGO_PKG_AUTHORS": ":".join(package.get("authors", [])), "CARGO_PKG_DESCRIPTION": package.get("description") or "", "CARGO_PKG_HOMEPAGE": package.get("homepage") or "", "CARGO_PKG_REPOSITORY": package.get("repository") or "", "CARGO_PKG_LICENSE": package.get("license") or "", "CARGO_PKG_RUST_VERSION": package.get("rust_version") or ""}
        attrs["rust_flags"] = unit["rust_flags"]
        attrs["emit_cdylib"] = unit["emit_cdylib"]
        attrs["compiler_env"] = unit.get("compiler_env", {})
        if unit["mode"] == "run-custom-build":
            attrs["compiler_env"] = {**attrs["compiler_env"], **custom_cfg_env(unit["rust_flags"])}
        macro_inputs = json.loads(source_inputs_file.read_text())["macros"].get(package.get("manifest"), [])
        attrs["macro_data"] = [source_file_label(path) for path in sorted(set(macro_inputs + unit.get("diagnostic_macro_inputs", [])))]
        attrs["runtime_tools"] = {"MERKUR_BROWSER_REGISTRATION_ORACLE": "//packages/merkur-client-native:browser_registration_oracle"} if package["name"] == "merkur-client-native" and unit["mode"] == "test" else {}
        attrs["runtime_data"] = [source_file_label(path) for path in json.loads(runtime_inputs_file.read_text()).get(package["name"], [])] if unit["mode"] == "test" else []
        attrs["profile_data"] = unit.get("profile_data", [])
        attrs["semantic_metadata"] = unit.get("semantic_metadata", "")
        if unit["mode"] == "run-custom-build":
            if script is None:
                raise ValueError("missing build-script compiler unit")
            attrs.update(script=script, pkg_name=package["name"], links=package["links"], profile=unit["profile"], build_data=metadata_projections, build_script_env_files=metadata_projections)
            if package["name"] == "merkur-identity-seal" and attrs["platform"] in ("aarch64-apple-darwin", "x86_64-apple-darwin"):
                attrs["swift_sdk"] = "//tools/bazel/tools/native:identity_swift_build_sdk"
        if unit["mode"] == "doctest":
            if crate is None:
                raise ValueError("doctest has no matching library unit")
            attrs["crate"] = crate
        if unit["mode"] not in ["build", "check", "test", "doctest", "run-custom-build"]:
            raise ValueError("unmodeled compiler mode " + unit["mode"])
        rule = "build_script_unit" if unit["mode"] == "run-custom-build" else "doctest_unit" if unit["mode"] == "doctest" else "compiler_unit"
        declaration = list(metadata_declarations)
        if unit["emit_cdylib"]:
            # rules_rust intentionally gives cdylibs an unmangled filename.
            # Put distinct configured cdylibs in distinct output packages.
            attrs["name"] = "cdylib"
            for name in ["deps", "proc_macro_deps"]:
                attrs[name] = ["//tools/bazel/rust/units" + label for label in attrs[name]]
            for name in ["aliases", "proc_macro_aliases"]:
                attrs[name] = {"//tools/bazel/rust/units" + label: alias for label, alias in attrs[name].items()}
            declaration = [HEADER, 'load("//tools/bazel/rust:units.bzl", "compiler_unit")\npackage(default_visibility = ["//visibility:public"])\nfilegroup(name = "verification_inputs", srcs = glob(["**"], exclude = [".*", "**/.*", ".*/**", "**/.*/**", "__pycache__/**", "**/__pycache__/**", "*.pyc", "**/*.pyc", ".env", ".env.*", "**/.env", "**/.env.*", ".bazelrc.local", "**/.bazelrc.local", ".DS_Store", "**/.DS_Store"]))\n\n']
        declaration.append(rule + "(\n")
        for name, value in attrs.items():
            if value is not None:
                declaration.append("    " + name + " = " + starlark(value) + ",\n")
        declaration.append(")\n\n")
        if unit["emit_cdylib"]:
            separate[DEST / unit_key / "BUILD.bazel"] = "".join(declaration)
            unit_source_groups.append("//tools/bazel/rust/units/" + unit_key + ":verification_inputs")
            build.append('alias(name = "u_' + unit_key + '", actual = "//tools/bazel/rust/units/' + unit_key + ':cdylib", tags = ["manual"])\n\n')
        else:
            build.extend(declaration)
    return separate, unit_source_groups


def render(nodes, roots, packages):
    checksums = locked_checksums(ROOT)
    archive_packages = {unit["pkg_id"]: packages[unit["pkg_id"]] for unit in nodes.values()}
    for snapshot in sorted((HERE / "policy_snapshots").glob("*.json")):
        policy = json.loads(snapshot.read_text())["metadata"]
        for fact in policy["merkur_registry_index"]:
            identity = fact["name"], fact["version"], "registry+https://github.com/rust-lang/crates.io-index"
            if identity in checksums and checksums[identity] != fact["checksum"]:
                raise ValueError("compiler/policy locked source checksum disagreement")
            checksums[identity] = fact["checksum"]
        for package in policy["packages"]:
            archive_packages.setdefault(package["id"], package)
    sources = [HEADER, 'archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")\n\n']
    for package_id in sorted(archive_packages):
        package = archive_packages[package_id]
        if package["source"] is None:
            continue
        if package["source"] != "registry+https://github.com/rust-lang/crates.io-index":
            raise ValueError("unmodeled locked source " + package["source"])
        name, version = package["name"], package["version"]
        digest = checksums[name, version, package["source"]]
        if not digest:
            raise ValueError("registry archive has no locked checksum")
        sources += ["archive(\n", "    name = " + text(source_repository(package)) + ",\n", "    urls = " + text([f"https://static.crates.io/crates/{name}/{name}-{version}.crate"]) + ",\n", "    sha256 = " + text(digest) + ",\n", "    strip_prefix = " + text(name + "-" + version) + ",\n", '    type = "tar.gz",\n', '    build_file = "//tools/bazel/rust:crate_sources.BUILD.bazel",\n', ")\n\n"]
    build = [HEADER, 'load("//tools/bazel/rust:units.bzl", "compiler_unit", "build_script_unit", "doctest_unit", "wasm_artifact", "configured_clippy_test", "build_script_metadata")\n\n', 'package(default_visibility = ["//visibility:public"])\n\n', 'exports_files(["graph.json"])\nfilegroup(name = "verification_inputs", srcs = glob(["**"], exclude = [".*", "**/.*", ".*/**", "**/.*/**", "__pycache__/**", "**/__pycache__/**", "*.pyc", "**/*.pyc", ".env", ".env.*", "**/.env", "**/.env.*", ".bazelrc.local", "**/.bazelrc.local", ".DS_Store", "**/.DS_Store"]))\n\n']
    for triple, cpu, os_name in [
        ("aarch64-apple-darwin", "aarch64", "macos"),
        ("x86_64-apple-darwin", "x86_64", "macos"),
        ("aarch64-unknown-linux-gnu", "aarch64", "linux"),
        ("x86_64-unknown-linux-gnu", "x86_64", "linux"),
    ]:
        build.append('config_setting(name = "native_' + identifier(triple) + '", constraint_values = ["@platforms//cpu:' + cpu + '", "@platforms//os:' + os_name + '"])\n')
        build.append('config_setting(name = "release_' + identifier(triple) + '", values = {"compilation_mode": "opt"}, constraint_values = ["@platforms//cpu:' + cpu + '", "@platforms//os:' + os_name + '"])\n')
    build.append('alias(name = "zstd_fixture__release_native", actual = select({' + ', '.join(text(":native_" + identifier(triple)) + ": " + text(":zstd_fixture__release__" + identifier(triple) + "__0") for triple in ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]) + '}), tags = ["manual"])\n\n')
    build.append('config_setting(name = "wasm", constraint_values = ["@platforms//cpu:wasm32", "@platforms//os:none"])\nconfig_setting(name = "release_wasm", values = {"compilation_mode": "opt"}, constraint_values = ["@platforms//cpu:wasm32", "@platforms//os:none"])\n')
    build.append('config_setting(name = "darwin_confinement", constraint_values = ["@platforms//os:macos"])\n')
    separate, unit_source_groups = _unit_declarations(nodes, packages, build, HERE / "metadata.json", HERE / "source_inputs.json", HERE / "runtime_inputs.json")
    clippy_targets = []
    coverage = []
    workspace_tests = []
    workspace_helpers = []
    workspace_checks = []
    fuzz_harnesses = {}
    fuzz_flags = None
    for name, labels in sorted(roots.items()):
        if name.startswith("bolero:"):
            package_name, profile, triple = name.split("/")
            candidates = [label for label in labels if nodes[label]["mode"] == "test" and packages[nodes[label]["pkg_id"]]["name"] == package_name.removeprefix("bolero:") + "-fuzz" and (nodes[label]["target"]["name"] == "fuzz" or package_name == "bolero:term-wasm")]
            if len(candidates) != 1:
                raise ValueError("ambiguous instrumented fuzz engine harness")
            fuzz_harnesses[package_name.removeprefix("bolero:")] = ":u_" + candidates[0] + "_binary"
            candidate_flags = nodes[candidates[0]]["rust_flags"]
            if fuzz_flags is not None and candidate_flags != fuzz_flags:
                raise ValueError("different fuzz instrumentation configurations in a campaign")
            fuzz_flags = candidate_flags
        if name.startswith("workspace-check/"):
            workspace_checks.extend(":u_" + label for label in labels)
        if name.startswith("workspace-test/"):
            for label in labels:
                (workspace_tests if nodes[label]["mode"] in ["test", "doctest"] else workspace_helpers).append(":u_" + label)
        if name.startswith("workspace-clippy/"):
            for index, label in enumerate(labels):
                unit = nodes[label]
                target = ":u_" + label + ("_binary" if unit["mode"] == "test" else "")
                clippy_name = "clippy__" + str(index)
                clippy_targets.append(":" + clippy_name)
                build.append("configured_clippy_test(name = " + text(clippy_name) + ", target = " + text(target) + ", platform = " + text(unit["platform"] or unit["execution_host"]) + ",)\n")
                coverage.append({"context": name, "operation": "clippy", "label": "//tools/bazel/rust/units:" + clippy_name, "unit": label, "owner_manifest": packages[unit["pkg_id"]]["manifest"], "profile": unit["profile"], "target": unit["platform"] or unit["execution_host"], "execution_host": unit["execution_host"], "production_execution_qualified": False})
        for index, label in enumerate(labels):
            public_label = identifier(name.replace("/", "__")) + "__" + str(index)
            public_name = text(public_label)
            unit = nodes[label]
            coverage.append({"context": name, "operation": "check" if unit["mode"] == "check" else "doctest" if unit["mode"] == "doctest" else "test" if unit["mode"] == "test" else "build", "label": "//tools/bazel/rust/units:" + ("u_" + label if unit["mode"] in ["test", "doctest"] else public_label), "configured_facade": "//tools/bazel/rust/units:" + public_label, "unit": label, "owner_manifest": packages[unit["pkg_id"]]["manifest"], "profile": unit["profile"], "target": unit["platform"] or unit["execution_host"], "execution_host": unit["execution_host"], "configured_native_receipt": unit["execution_host"] in native_receipts.HOSTS and name.startswith("merkur-fec/"), "production_execution_qualified": False})
            if nodes[label]["mode"] in ["test", "doctest"]:
                build.append("test_suite(name = " + public_name + ", tests = [\":u_" + label + '\"], tags = ["manual"])\n')
            else:
                build.append("alias(name = " + public_name + ", actual = \":u_" + label + '\", tags = ["manual"])\n')
        package_name, profile, triple = name.split("/")
        if package_name == "browser-session-oracle":
            if len(labels) != 1 or nodes[labels[0]]["target"]["name"] != "browser_session_oracle":
                raise ValueError("incorrect native Session oracle root")
            build.append('alias(name = "browser_session_oracle__native", actual = ":u_' + labels[0] + '", tags = ["manual"])\n')
        if triple == "wasm32-unknown-unknown" and profile in ["release", "instrumented", "profile_use"]:
            cdylibs = [label for label in labels if nodes[label]["emit_cdylib"]]
            if len(cdylibs) == 1:
                qualification = profile if profile != "release" else "unprofiled" if package_name == "term-wasm" else "uninstrumented" if package_name == "term-wasm-pgo" else "release"
                build.append("wasm_artifact(name = " + text(identifier(package_name) + "__" + qualification + "_wasm") + ", target = \":u_" + cdylibs[0] + '\", tags = ["manual"])\n')
    build.append("filegroup(name = \"workspace_check\", srcs = " + starlark(workspace_checks) + ", tags = [\"manual\"])\n")
    build.append("test_suite(name = \"workspace_clippy\", tests = " + starlark(clippy_targets) + ", tags = [\"manual\"])\n")
    build.append("test_suite(name = \"workspace_test\", tests = " + starlark(workspace_tests) + ", tags = [\"manual\"])\n")
    build.append("filegroup(name = \"workspace_test_helpers\", srcs = " + starlark(workspace_helpers) + ", tags = [\"manual\"])\n")
    build.insert(1, 'load("//tools/bazel/rust:fuzz.bzl", "declare_fuzz_campaigns")\n')
    build.append("declare_fuzz_campaigns(" + starlark(fuzz_harnesses) + ", " + starlark(fuzz_flags) + ")\n")
    provenance_build = [HEADER, 'package(default_visibility = ["//visibility:public"])\nexports_files(glob(["*.json"]))\nfilegroup(name = "verification_inputs", srcs = glob(["**"], exclude = [".*", "**/.*", ".*/**", "**/.*/**", "__pycache__/**", "**/__pycache__/**", "*.pyc", "**/*.pyc", ".env", ".env.*", "**/.env", "**/.env.*", ".bazelrc.local", "**/.bazelrc.local", ".DS_Store", "**/.DS_Store"]))\n']
    notice_facts = license_metadata.check()
    provenance_requests = [("term-wasm", "instrumented", "term-wasm/instrumented/wasm32-unknown-unknown"), ("term-wasm", "profile_use", "term-wasm/profile_use/wasm32-unknown-unknown"), ("browser-session-oracle", "native", next(name for name in roots if name.startswith("browser-session-oracle/")))]
    for shipping_package in ["merkur-dataplane", "merkur-tui", "merkur-image-worker", "merkur-edge", "merkur-stun"]:
        for triple in ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]:
            provenance_requests.append((shipping_package, "_release__" + identifier(triple), shipping_package + "/release/" + triple))
    # Project the actual shipped WASM roots and their loaded host macros from
    # the same captured DAG. These projections never create compiler units.
    attribution_roots = {}
    for package, profile in [("e2e-wasm", "release"), ("graphics-wasm", "release"), ("term-wasm", "profile_use")]:
        context = package + "/" + profile + "/wasm32-unknown-unknown"
        selected = [identity for identity in roots[context] if nodes[identity]["emit_cdylib"]]
        if len(selected) != 1:
            raise ValueError("shipped WASM descriptor requires exactly its actual cdylib root")
        variant = "selected_" + profile + "_wasm"
        provenance_requests.append((package, variant, context))
        attribution_roots[(package, variant)] = selected
        pending, seen = list(selected), set()
        while pending:
            identity = pending.pop()
            if identity in seen:
                continue
            seen.add(identity)
            unit = nodes[identity]
            if unit["target"]["kind"] == ["proc-macro"]:
                if unit["mode"] != "build" or unit["profile"]["name"] != "release" or unit["platform"] is not None:
                    raise ValueError("loaded host macro lacks its actual native release configuration")
                attribution_roots[("host-proc-macro", identity)] = [identity]
            pending.extend(edge["unit"] for edge in unit["dependencies"])
    for package, variant in sorted(attribution_roots):
        if package == "host-proc-macro":
            provenance_requests.append((package, variant, "host-proc-macro/" + variant))
    for package, variant, context in provenance_requests:
        shipping = variant.startswith("_release__")
        selected_attribution = shipping or (package, variant) in attribution_roots
        root_ids = attribution_roots.get((package, variant), roots.get(context))
        if shipping:
            root_ids = [unit_key for unit_key in root_ids if nodes[unit_key]["target"]["name"] == package and nodes[unit_key]["target"]["crate_types"] == ["bin"]]
            if len(root_ids) != 1:
                raise ValueError("shipping descriptor must select exactly its named native binary")
        closure = {}
        def include(unit_key):
            if unit_key in closure:
                return
            unit = nodes[unit_key]
            closure[unit_key] = unit
            for edge in unit["dependencies"]:
                include(edge["unit"])
        for unit_key in root_ids:
            include(unit_key)
        descriptor_name = identifier(package) + "_" + variant
        descriptor = {"roots": root_ids, "units": closure, "macro_inputs": {package_id: json.loads((HERE / "source_inputs.json").read_text())["macros"].get(packages[package_id].get("manifest", ""), []) for package_id in sorted({unit["pkg_id"] for unit in closure.values()})}, "packages": {package_id: packages[package_id] for package_id in sorted({unit["pkg_id"] for unit in closure.values()})}}
        if selected_attribution:
            for package_id, package_info in descriptor["packages"].items():
                notice = notice_facts[package_id]
                if any(package_info[field] != notice[field] for field in ["name", "version", "source", "license", "repository"]):
                    raise ValueError("shipping compiler and locked notice package identities differ: " + package_id)
                descriptor["packages"][package_id] = dict(package_info, license_file=notice["license_file"], archive_checksum=checksums.get((package_info["name"], package_info["version"], package_info["source"])))
            descriptor["configuration"] = {"compiler_root": context, "target": (nodes[root_ids[0]]["platform"] or nodes[root_ids[0]]["execution_host"]) if not shipping else context.split("/")[-1], "captured_execution_hosts": sorted({unit["execution_host"] for unit in closure.values()}), "public_release_context": "//tools/bazel/bun:public_release_context"}
            descriptor["package_sources"] = {package_id: source(package_info) + ":package_data" for package_id, package_info in descriptor["packages"].items()}
            descriptor["package_manifests"] = {package_id: source_file_label(package_info["manifest"]) if package_info["source"] is None else source(package_info) + ":Cargo.toml" for package_id, package_info in descriptor["packages"].items()}
            descriptor["license_sources"] = {"workspace": {"manifest": "//:Cargo.toml", "text": "//:LICENSE"}, "packages": descriptor["package_sources"]}
            descriptor["shipping_qualified"] = False
            descriptor["pending"] = ["Native release PGO and SDK/compiler receipts", "Configured Cargo resolution on every supported execution host", "Compiled public account-pin and release configuration assertions"]
        membership = {str((DEST / "provenance" / (descriptor_name + ".json")).relative_to(ROOT))}
        labels = [":" + descriptor_name + ".json", "//:Cargo.toml", "//:Cargo.lock", "//:rust-toolchain.toml", "//:MODULE.bazel", "//:.cargo/config.toml", "//packages/term-wasm:.cargo/config.toml", "//tools/bazel/rust:units.bzl", "//tools/bazel/rust:units.py", "//tools/bazel/rust:contexts.py", "//tools/bazel/rust:llvm_tools.bzl", "//tools/bazel/rust:rust.MODULE.bazel", "//tools/bazel/rust:source_inputs.json", "//tools/bazel/rust:source_inputs.rs", "//tools/bazel/worker:rules_rust-0.74.0.patch", "//tools/bazel/cc:cc.MODULE.bazel", "//tools/bazel/cc:wasm_config.bzl", "//tools/bazel/cc:sdk.BUILD.bazel", "//tools/bazel/bun:BUILD.bazel", "//tools/bazel/bun:rules.bzl", "//tools/bazel/bun:public-release-context.ts"]
        if package == "term-wasm":
            resolution = "training" if variant == "instrumented" else "build"
            resolution_owner = "//tools/bazel/rust/contexts/term-wasm/" + resolution + "/wasm:"
            descriptor["resolution_context"] = resolution_owner + "metadata.json"
            labels += [resolution_owner + name for name in ["Cargo.toml", "Cargo.lock", "metadata.json", "BUILD.bazel"]]
        if selected_attribution:
            labels += ["//:LICENSE", "//tools/bazel/rust:license_metadata.py", "//tools/bazel/rust:license_metadata.json"]
            provenance_build.append('filegroup(name = ' + text(descriptor_name + "_package_sources") + ', srcs = ' + starlark(sorted(descriptor["package_sources"].values())) + ')\n')
        if package == "browser-session-oracle":
            labels = [label for label in labels if label not in ["//packages/term-wasm:.cargo/config.toml", "//tools/bazel/rust:llvm_tools.bzl", "//tools/bazel/cc:cc.MODULE.bazel", "//tools/bazel/cc:wasm_config.bzl", "//tools/bazel/cc:sdk.BUILD.bazel"]]
            labels += ["//tools/bazel/rust:native_oracle.py", "//tools/bazel/rust:diagnostics/oracles/browser-session-oracle.json"]
        for package_id in descriptor["packages"]:
            package_info = packages[package_id]
            if package_info["source"] is None:
                prefix = source(package_info)
                labels += [prefix + ":rust_sources", prefix + ":Cargo.toml", prefix + ":BUILD.bazel"]
                labels += [source_file_label(path) for path in descriptor["macro_inputs"][package_id]]
                directory = Path(package_info["manifest"]).parent
                membership.update(path for path in json.loads((HERE / "source_inputs.json").read_text())["sources"] if Path(path).is_relative_to(directory))
                membership.update(descriptor["macro_inputs"][package_id])
        for label in labels:
            if label.startswith("//") and not label.endswith(":rust_sources"):
                owner, name = label.removeprefix("//").split(":", 1)
                membership.add(str(Path(owner) / name))
        descriptor["source_membership"] = sorted(membership)
        separate[DEST / "provenance" / (descriptor_name + ".json")] = json.dumps(descriptor, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
        if variant == "profile_use":
            labels += ["//packages/term-wasm:terminal_profile"]
        provenance_build.append('filegroup(name = ' + text(descriptor_name + "_sources") + ', srcs = ' + starlark(sorted(set(labels))) + ')\n')
    separate[DEST / "provenance" / "BUILD.bazel"] = "".join(provenance_build)
    build.append('exports_files(["coverage.json"])\n')
    return {**separate, DEST / "source_groups.bzl": HEADER + "UNIT_SOURCE_GROUPS = " + starlark(sorted(unit_source_groups)) + "\n", HERE / "operation_bindings.bzl": operation_bindings(coverage, packages), HERE / "package_targets.bzl": package_facades(nodes, roots, packages), HERE / "sources.MODULE.bazel": "".join(sources), DEST / "BUILD.bazel": "".join(build), DEST / "graph.json": json.dumps({"nodes": nodes, "roots": roots}, sort_keys=True, indent=2) + "\n", DEST / "coverage.json": json.dumps({"targets": coverage, "pending": ["Complete four-host production/test/runtime qualification", "Native configured workspace Clippy/full unit inventory", "Protocol and assurance operation bindings are separate declared suites"]}, sort_keys=True, indent=2) + "\n"}


def main():
    macro_document = json.loads((HERE / "source_inputs.json").read_text())
    if hashlib.sha256((HERE / "metadata.json").read_bytes()).hexdigest() != macro_document["metadata_sha256"]:
        raise ValueError("stale Rust macro metadata inventory")
    metadata = json.loads((HERE / "metadata.json").read_text())
    current_sources = set()
    for package in metadata["packages"]:
        if "manifest" not in package:
            continue
        directory = (ROOT / package["manifest"]).parent
        for path in directory.rglob("*.rs"):
            if any(part in {"target", "node_modules", "pkg", "dist", ".git"} for part in path.relative_to(directory).parts):
                continue
            current_sources.add(str(path.relative_to(ROOT)))
    if current_sources != set(macro_document["sources"]):
        raise ValueError("Rust macro source inventory changed; refresh exact discovery")
    for path, expected in macro_document["sources"].items():
        if hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != expected:
            raise ValueError("stale Rust macro input discovery: " + path)
    for path, expected in macro_document["included_sources"].items():
        if hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != expected:
            raise ValueError("stale recursively included Rust source discovery: " + path)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true")
    parser.add_argument("--package", action="append")
    args = parser.parse_args()
    documents = [path for path in (HERE / "contexts").glob("*/*/*/metadata.json") if not args.package or path.parts[-4] in args.package]
    documents += list((HERE / "diagnostics/bolero").glob("*.json"))
    documents += list((HERE / "diagnostics/oracles").glob("*.json"))
    if not documents:
        raise ValueError("no retained configured compiler graphs")
    nodes, roots, packages = collect(documents, native_receipts.load())
    terminal_variants(nodes, roots)
    outputs = render(nodes, roots, packages)
    obsolete_provenance = set((DEST / "provenance").glob("*.json")) - set(outputs)
    if obsolete_provenance:
        raise ValueError("obsolete compiler provenance declarations: " + ", ".join(str(path) for path in sorted(obsolete_provenance)))
    if args.refresh:
        for old in DEST.glob("*/BUILD.bazel"):
            if old not in outputs:
                if not old.read_text().startswith(HEADER):
                    raise ValueError("refusing to remove a non-generated unit package")
                old.unlink()
                old.parent.rmdir()
    for path, body in outputs.items():
        if args.refresh:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
        elif not path.exists() or (json.loads(path.read_text()) != json.loads(body) if path == DEST / "coverage.json" else path.read_text() != body):
            raise ValueError("stale native compiler declarations: " + str(path))
    print(f"Native Rust graph checked: {len(nodes)} canonical units, {len(roots)} configured roots")
    return 0


if __name__ == "__main__":
    sys.exit(main())
