rolldown_vite_raw_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
rolldown_vite_raw_archive(
    name = "rolldown_registry_a88cf1f829d945f548cf8fec32c61b1f202b6d93b45848602fc02af4b12ad218",
    urls = ["https://static.crates.io/crates/futures/futures-0.3.33.crate"],
    sha256 = "a88cf1f829d945f548cf8fec32c61b1f202b6d93b45848602fc02af4b12ad218",
    downloaded_file_path = "futures-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_262590f4fe6afeb0bc83be1daa64e52657fe185690a958af7f3ad0e92085c5ae",
    urls = ["https://static.crates.io/crates/futures-channel/futures-channel-0.3.33.crate"],
    sha256 = "262590f4fe6afeb0bc83be1daa64e52657fe185690a958af7f3ad0e92085c5ae",
    downloaded_file_path = "futures-channel-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_2cd50c473c80f6d7c3670a752354b8e569b1a7cbfdc0419ec88e5edad85e0dc7",
    urls = ["https://static.crates.io/crates/futures-core/futures-core-0.3.33.crate"],
    sha256 = "2cd50c473c80f6d7c3670a752354b8e569b1a7cbfdc0419ec88e5edad85e0dc7",
    downloaded_file_path = "futures-core-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_6754879cc9f2c66f88c6e5c35344bb0bdb0708b0352b1201815667c7eabc7458",
    urls = ["https://static.crates.io/crates/futures-executor/futures-executor-0.3.33.crate"],
    sha256 = "6754879cc9f2c66f88c6e5c35344bb0bdb0708b0352b1201815667c7eabc7458",
    downloaded_file_path = "futures-executor-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_4577ecaa3c4f96589d473f679a71b596316f6641bc350038b962a5daf0085d7a",
    urls = ["https://static.crates.io/crates/futures-io/futures-io-0.3.33.crate"],
    sha256 = "4577ecaa3c4f96589d473f679a71b596316f6641bc350038b962a5daf0085d7a",
    downloaded_file_path = "futures-io-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_2d6d3cde68c518367be28956066ddfef33813991b77a55005a69dae04bf3b10b",
    urls = ["https://static.crates.io/crates/futures-macro/futures-macro-0.3.33.crate"],
    sha256 = "2d6d3cde68c518367be28956066ddfef33813991b77a55005a69dae04bf3b10b",
    downloaded_file_path = "futures-macro-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_e34418ac499d6305c2fb5ad0ed2f6ac998c5f8ca209b4510f7f94242c647e307",
    urls = ["https://static.crates.io/crates/futures-sink/futures-sink-0.3.33.crate"],
    sha256 = "e34418ac499d6305c2fb5ad0ed2f6ac998c5f8ca209b4510f7f94242c647e307",
    downloaded_file_path = "futures-sink-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_b231ed28831efb4a61a08580c4bc233ec56bc009f4cd8f52da2c3cb97df0c109",
    urls = ["https://static.crates.io/crates/futures-task/futures-task-0.3.33.crate"],
    sha256 = "b231ed28831efb4a61a08580c4bc233ec56bc009f4cd8f52da2c3cb97df0c109",
    downloaded_file_path = "futures-task-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_a77a90a256fce34da66415271e30f94ee91c57b04b8a2c042d9cf3220179deaa",
    urls = ["https://static.crates.io/crates/futures-util/futures-util-0.3.33.crate"],
    sha256 = "a77a90a256fce34da66415271e30f94ee91c57b04b8a2c042d9cf3220179deaa",
    downloaded_file_path = "futures-util-0.3.33.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_dbbeaf92280ba8365dc2f25390a388cfe74d48a6d3de6ff2f5ec6469777f8b92",
    urls = ["https://static.crates.io/crates/oxc/oxc-0.144.0.crate"],
    sha256 = "dbbeaf92280ba8365dc2f25390a388cfe74d48a6d3de6ff2f5ec6469777f8b92",
    downloaded_file_path = "oxc-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_50a403a3c6be65be7bc7730d07d959ec6c143e4ff8117da485df78cd5582260a",
    urls = ["https://static.crates.io/crates/oxc-browserslist/oxc-browserslist-3.0.11.crate"],
    sha256 = "50a403a3c6be65be7bc7730d07d959ec6c143e4ff8117da485df78cd5582260a",
    downloaded_file_path = "oxc-browserslist-3.0.11.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_330e07b3807046e0afa8fcc94f1fe976e93831b370d148bfe1168cb53da1b913",
    urls = ["https://static.crates.io/crates/oxc-miette/oxc-miette-4.0.0.crate"],
    sha256 = "330e07b3807046e0afa8fcc94f1fe976e93831b370d148bfe1168cb53da1b913",
    downloaded_file_path = "oxc-miette-4.0.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_9262c7bbd58c8c32c2c60d1a7b6c274cd2aeaff1b726a2fb86081b75084698cb",
    urls = ["https://static.crates.io/crates/oxc_allocator/oxc_allocator-0.144.0.crate"],
    sha256 = "9262c7bbd58c8c32c2c60d1a7b6c274cd2aeaff1b726a2fb86081b75084698cb",
    downloaded_file_path = "oxc_allocator-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_e8134809b665d524d9a0ddeee87a5d3602776aa2410a10a0439fd25eeb594a5d",
    urls = ["https://static.crates.io/crates/oxc_ast/oxc_ast-0.144.0.crate"],
    sha256 = "e8134809b665d524d9a0ddeee87a5d3602776aa2410a10a0439fd25eeb594a5d",
    downloaded_file_path = "oxc_ast-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_ac120c6863a9d036c78a42a5e4d2f58bb27c5df795d61d904f6e19e48c681a37",
    urls = ["https://static.crates.io/crates/oxc_ast_macros/oxc_ast_macros-0.144.0.crate"],
    sha256 = "ac120c6863a9d036c78a42a5e4d2f58bb27c5df795d61d904f6e19e48c681a37",
    downloaded_file_path = "oxc_ast_macros-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_4a57626cd6ef87f5173110a301868e3c438fd8e0576f489d9a61540ef133f686",
    urls = ["https://static.crates.io/crates/oxc_ast_visit/oxc_ast_visit-0.144.0.crate"],
    sha256 = "4a57626cd6ef87f5173110a301868e3c438fd8e0576f489d9a61540ef133f686",
    downloaded_file_path = "oxc_ast_visit-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_5f8a30cbe510caef092aa75fe29e8d37576ca8eb2ab3e9ab34a453a92863e7f0",
    urls = ["https://static.crates.io/crates/oxc_codegen/oxc_codegen-0.144.0.crate"],
    sha256 = "5f8a30cbe510caef092aa75fe29e8d37576ca8eb2ab3e9ab34a453a92863e7f0",
    downloaded_file_path = "oxc_codegen-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_2ca8b4e5fc1b038d063aef726deeb0639460b0a3f4dfa9cc3f1b52b4b231bbf7",
    urls = ["https://static.crates.io/crates/oxc_compat/oxc_compat-0.144.0.crate"],
    sha256 = "2ca8b4e5fc1b038d063aef726deeb0639460b0a3f4dfa9cc3f1b52b4b231bbf7",
    downloaded_file_path = "oxc_compat-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_2a71efea56db93d3ce9e88e1d9f74f6d50fc2b06092444cdd08579f5827fd8db",
    urls = ["https://static.crates.io/crates/oxc_data_structures/oxc_data_structures-0.144.0.crate"],
    sha256 = "2a71efea56db93d3ce9e88e1d9f74f6d50fc2b06092444cdd08579f5827fd8db",
    downloaded_file_path = "oxc_data_structures-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_e5ff8638533094ecdcd38a63930c003c261d81650e4531c3bc805c797aec2a52",
    urls = ["https://static.crates.io/crates/oxc_diagnostics/oxc_diagnostics-0.144.0.crate"],
    sha256 = "e5ff8638533094ecdcd38a63930c003c261d81650e4531c3bc805c797aec2a52",
    downloaded_file_path = "oxc_diagnostics-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_77c7a326f49f06da37affdcad2fb3ebab46ac4ada8953a428f7cbd04e5cc9e6e",
    urls = ["https://static.crates.io/crates/oxc_ecmascript/oxc_ecmascript-0.144.0.crate"],
    sha256 = "77c7a326f49f06da37affdcad2fb3ebab46ac4ada8953a428f7cbd04e5cc9e6e",
    downloaded_file_path = "oxc_ecmascript-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_8275fcb9674a1c320f0bdbc2f534ba9bb09fcb8b1c9fe306c9595d262a06bfcb",
    urls = ["https://static.crates.io/crates/oxc_estree/oxc_estree-0.144.0.crate"],
    sha256 = "8275fcb9674a1c320f0bdbc2f534ba9bb09fcb8b1c9fe306c9595d262a06bfcb",
    downloaded_file_path = "oxc_estree-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_aba22c46bf2b6dc717be28b0cb5bfdd7c6dadb81b6ff47e3bee85ba0a9637733",
    urls = ["https://static.crates.io/crates/oxc_isolated_declarations/oxc_isolated_declarations-0.144.0.crate"],
    sha256 = "aba22c46bf2b6dc717be28b0cb5bfdd7c6dadb81b6ff47e3bee85ba0a9637733",
    downloaded_file_path = "oxc_isolated_declarations-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_0d44069ca70dbae736cd232b04fe21f5ed354396be2365b5ed16adcf86248a09",
    urls = ["https://static.crates.io/crates/oxc_mangler/oxc_mangler-0.144.0.crate"],
    sha256 = "0d44069ca70dbae736cd232b04fe21f5ed354396be2365b5ed16adcf86248a09",
    downloaded_file_path = "oxc_mangler-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_edb4a27820aa9c98438a7ed41d72747690111fc2075fbd178e81f94e55ae16ea",
    urls = ["https://static.crates.io/crates/oxc_minifier/oxc_minifier-0.144.0.crate"],
    sha256 = "edb4a27820aa9c98438a7ed41d72747690111fc2075fbd178e81f94e55ae16ea",
    downloaded_file_path = "oxc_minifier-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_59664968ec86932143f0ce439d85b84f6193dab60678572d44c34a26a2f638db",
    urls = ["https://static.crates.io/crates/oxc_minify_napi/oxc_minify_napi-0.144.0.crate"],
    sha256 = "59664968ec86932143f0ce439d85b84f6193dab60678572d44c34a26a2f638db",
    downloaded_file_path = "oxc_minify_napi-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_c37292d00477aef3aa4abd697b0856c677ae992e50e41ba0435575ca69bc64d6",
    urls = ["https://static.crates.io/crates/oxc_napi/oxc_napi-0.144.0.crate"],
    sha256 = "c37292d00477aef3aa4abd697b0856c677ae992e50e41ba0435575ca69bc64d6",
    downloaded_file_path = "oxc_napi-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_d13016de81370106ea4065cfabe4a278dc09e82523cfe22bb6a8ab8e993b4c3a",
    urls = ["https://static.crates.io/crates/oxc_parser/oxc_parser-0.144.0.crate"],
    sha256 = "d13016de81370106ea4065cfabe4a278dc09e82523cfe22bb6a8ab8e993b4c3a",
    downloaded_file_path = "oxc_parser-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_db092436303bbd448889c4ca3cf122a6eebc7dac97aab695710b5619330b6c12",
    urls = ["https://static.crates.io/crates/oxc_parser_napi/oxc_parser_napi-0.144.0.crate"],
    sha256 = "db092436303bbd448889c4ca3cf122a6eebc7dac97aab695710b5619330b6c12",
    downloaded_file_path = "oxc_parser_napi-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_c375b89d88ec03301b0e62528715699551871861197aa39148e95a1422e1ae9b",
    urls = ["https://static.crates.io/crates/oxc_regular_expression/oxc_regular_expression-0.144.0.crate"],
    sha256 = "c375b89d88ec03301b0e62528715699551871861197aa39148e95a1422e1ae9b",
    downloaded_file_path = "oxc_regular_expression-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_0d8d80604c4220c8f5b1c19682216921397fb45a616db47d3a044474662f0c2e",
    urls = ["https://static.crates.io/crates/oxc_semantic/oxc_semantic-0.144.0.crate"],
    sha256 = "0d8d80604c4220c8f5b1c19682216921397fb45a616db47d3a044474662f0c2e",
    downloaded_file_path = "oxc_semantic-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_abd732008dbfb09984106925f7ff7268687c8020b89bd7ee0f0b695c5bb07950",
    urls = ["https://static.crates.io/crates/oxc_span/oxc_span-0.144.0.crate"],
    sha256 = "abd732008dbfb09984106925f7ff7268687c8020b89bd7ee0f0b695c5bb07950",
    downloaded_file_path = "oxc_span-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_e1d2ccb0f5aa4da9fc98ef70f59553c2779e28e064a8b271fcb1e88c11a63607",
    urls = ["https://static.crates.io/crates/oxc_str/oxc_str-0.144.0.crate"],
    sha256 = "e1d2ccb0f5aa4da9fc98ef70f59553c2779e28e064a8b271fcb1e88c11a63607",
    downloaded_file_path = "oxc_str-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_15ff0e987ab15a71dae36fd544b9859513e76639e2cc6c5e25895081162755b1",
    urls = ["https://static.crates.io/crates/oxc_syntax/oxc_syntax-0.144.0.crate"],
    sha256 = "15ff0e987ab15a71dae36fd544b9859513e76639e2cc6c5e25895081162755b1",
    downloaded_file_path = "oxc_syntax-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_2182d00b6cb0b1fce0d9a93f2f160ac88b14236d768c00a868d07e4bb59d1508",
    urls = ["https://static.crates.io/crates/oxc_transform_napi/oxc_transform_napi-0.144.0.crate"],
    sha256 = "2182d00b6cb0b1fce0d9a93f2f160ac88b14236d768c00a868d07e4bb59d1508",
    downloaded_file_path = "oxc_transform_napi-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_1f78841ae7b3fdeb86cbc6ee625e2ea844e663fd7b0b320cd361a8514eae34f7",
    urls = ["https://static.crates.io/crates/oxc_transformer/oxc_transformer-0.144.0.crate"],
    sha256 = "1f78841ae7b3fdeb86cbc6ee625e2ea844e663fd7b0b320cd361a8514eae34f7",
    downloaded_file_path = "oxc_transformer-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_ee9b1a4f823435ac5c089a8692a76887b16603ac33781a96f7925f5b0b86e102",
    urls = ["https://static.crates.io/crates/oxc_transformer_plugins/oxc_transformer_plugins-0.144.0.crate"],
    sha256 = "ee9b1a4f823435ac5c089a8692a76887b16603ac33781a96f7925f5b0b86e102",
    downloaded_file_path = "oxc_transformer_plugins-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_8cb740c9102d898615f894864044ca0b7926374981cef1b6c667e59e2b397ff9",
    urls = ["https://static.crates.io/crates/oxc_traverse/oxc_traverse-0.144.0.crate"],
    sha256 = "8cb740c9102d898615f894864044ca0b7926374981cef1b6c667e59e2b397ff9",
    downloaded_file_path = "oxc_traverse-0.144.0.crate",
)
rolldown_vite_raw_archive(
    name = "rolldown_registry_bf3923a6f5c4c6382e0b653c4117f48d631ea17f38ed86e2a828e6f7412f5239",
    urls = ["https://static.crates.io/crates/uuid/uuid-1.24.0.crate"],
    sha256 = "bf3923a6f5c4c6382e0b653c4117f48d631ea17f38ed86e2a828e6f7412f5239",
    downloaded_file_path = "uuid-1.24.0.crate",
)
