load("@aspect_rules_js//js:defs.bzl", "js_library")
load("//tools/bazel/bun:rules.bzl", "bun_binary", "bun_test")

package(default_visibility = ["//visibility:public"])

filegroup(name = "verification_inputs", srcs = glob(["**"], exclude = ["**/.*", "**/.*/**", "**/__pycache__/**", "**/*.pyc"]))

js_library(name = "tooling_sources", srcs = ["buildbuddy.ts", "buildbuddy.test.ts"])

bun_binary(
    name = "buildbuddy",
    entry_point = "buildbuddy.ts",
    bun_config = "//tools/bazel/bun:empty-bunfig.toml",
    data = ["//:js_configuration"],
)

bun_test(
    name = "buildbuddy_test",
    test_files = ["./tools/bazel/credentials/buildbuddy.test.ts"],
    bun_config = "//tools/bazel/bun:empty-bunfig.toml",
    data = ["buildbuddy.ts", "buildbuddy.test.ts", "//:js_configuration"],
)
