import '@merkur/shared/e2e-wasm-bun';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ColumnMetadata, TableMetadata } from 'kysely';

import { createMigratedKyselyDatabase } from '../src/db/migrate';

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const GENERATED_TYPES_PATH = path.resolve(SCRIPT_DIRECTORY, '../src/db/generated-types.ts');
const REPOSITORY_ROOT = path.resolve(SCRIPT_DIRECTORY, '../../..');
const BIOME_BINARY = path.join(REPOSITORY_ROOT, 'node_modules/.bin/biome');
const TEMP_PREFIX = path.join(os.tmpdir(), 'merkur-codegen-');
const TEMP_DATABASE_NAME = 'codegen.db';

const FILE_HEADER = `/**
 * This file was generated by apps/server/scripts/run-db-codegen.ts.
 * Please do not edit it manually.
 */
`;

/** A column the database fills in itself is optional on insert. */
const GENERATED_HELPER = `import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
`;

/** The SQLite column types the migrations declare, as the libSQL client returns them. */
const COLUMN_TYPES: Readonly<Record<string, string>> = {
  integer: 'number',
  text: 'string',
};

/** Names this shape map one way onto a TypeScript identifier and need no quoting as a key. */
const SNAKE_CASE_NAME = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;
/** Type names the generated file declares itself, which a table must not take. */
const RESERVED_TYPE_NAMES = ['DB', 'Generated'];

interface TableType {
  readonly table: string;
  readonly name: string;
  readonly declaration: string;
}

const tempDirectory = await mkdtemp(TEMP_PREFIX);
const tempDatabasePath = path.join(tempDirectory, TEMP_DATABASE_NAME);

try {
  await runCodegen(tempDatabasePath);
  await formatGeneratedTypes();
} finally {
  await rm(tempDirectory, { recursive: true, force: true });
}

/**
 * Introspects a freshly migrated database through the same libSQL client the
 * server runs on, so codegen needs no second SQLite driver.
 */
async function runCodegen(databasePath: string): Promise<void> {
  const db = await createMigratedKyselyDatabase<Record<string, never>>(`file:${databasePath}`);

  try {
    await writeFile(GENERATED_TYPES_PATH, renderTypes(await db.introspection.getTables()));
  } finally {
    await db.destroy();
  }
}

/** One interface per table, then the `DB` interface that maps each table to its own. */
function renderTypes(tables: readonly TableMetadata[]): string {
  const types = tables.map(renderTable);
  const declared = new Set(RESERVED_TYPE_NAMES);
  for (const { name, table } of types) {
    // TypeScript merges two interfaces of one name instead of rejecting them.
    if (declared.has(name)) throw new Error(`Table ${table} repeats the type name ${name}`);
    declared.add(name);
  }

  const usesGenerated = tables.some((table) => table.columns.some(isGenerated));
  const interfaces = [...types]
    .sort((left, right) => compareCodeUnits(left.name, right.name))
    .map((type) => type.declaration);
  const database = [...types]
    .sort((left, right) => compareCodeUnits(left.table, right.table))
    .map((type) => `  ${type.table}: ${type.name};\n`)
    .join('');

  return [
    FILE_HEADER,
    ...(usesGenerated ? [GENERATED_HELPER] : []),
    ...interfaces,
    `export interface DB {\n${database}}\n`,
  ].join('\n');
}

function renderTable(table: TableMetadata): TableType {
  const name = typeName(table.name);
  const columns = [...table.columns]
    .sort((left, right) => compareCodeUnits(left.name, right.name))
    .map((column) => `  ${requireSnakeCase(column.name)}: ${columnType(table.name, column)};\n`)
    .join('');
  return { table: table.name, name, declaration: `export interface ${name} {\n${columns}}\n` };
}

function columnType(table: string, column: ColumnMetadata): string {
  const type = COLUMN_TYPES[column.dataType.toLowerCase()];
  if (type === undefined) {
    throw new Error(
      `${table}.${column.name} has the SQLite type ${column.dataType}; give it a TypeScript type in COLUMN_TYPES`,
    );
  }
  const value = column.isNullable ? `${type} | null` : type;
  return isGenerated(column) ? `Generated<${value}>` : value;
}

function isGenerated(column: ColumnMetadata): boolean {
  return column.hasDefaultValue || column.isAutoIncrementing;
}

/** `daemon_link_claims` becomes `DaemonLinkClaims`. */
function typeName(table: string): string {
  return requireSnakeCase(table)
    .split('_')
    .map((word) => `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`)
    .join('');
}

function requireSnakeCase(name: string): string {
  if (!SNAKE_CASE_NAME.test(name)) throw new Error(`${name} is not a snake_case name`);
  return name;
}

/** Orders by UTF-16 code unit, which no locale changes. */
function compareCodeUnits(left: string, right: string): number {
  if (left < right) return -1;
  return left > right ? 1 : 0;
}

/** The generator emits unformatted text, so hand the result to Biome. */
function formatGeneratedTypes(): Promise<void> {
  return runCommand(BIOME_BINARY, ['check', '--write', GENERATED_TYPES_PATH]);
}

async function runCommand(command: string, args: string[]): Promise<void> {
  const childProcess = Bun.spawn([command, ...args], {
    stdin: 'inherit',
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await childProcess.exited;
  if (code !== 0) {
    throw new Error(`${command} exited with code ${String(code)}`);
  }
}
